In [10]:
from siuba import *
from plotnine import *
from calitp.tables import tbl

##for all the feeds we consume, how many publish the following fields?

In [12]:
tbl_feed_info = (tbl.gtfs_schedule.feed_info())

In [13]:
tbl_stops = (tbl.gtfs_schedule.stops())

In [47]:
tbl_feed_stops = (
    tbl_stops
    >>left_join (
        _,  tbl_feed_info, ["calitp_itp_id", "calitp_url_number"],
    )
    >> inner_join(_, tbl.views.gtfs_agency_names(), ["calitp_itp_id", "calitp_url_number"])
)

In [ ]:
## it appears we dont log any tts_stop name

In [ ]:
#SELECT tts_stop_name, COUNT(*) AS n FROM `cal-itp-data-infra.gtfs_schedule.stops` GROUP BY 1

In [39]:
stop_name_counts = (tbl_feed_stops 
   >> count(_.calitp_itp_id, _.calitp_url_number, _.agency_name, has_stop_name = _.tts_stop_name.notna())
)

In [46]:
(tbl_feed_stops
  >> group_by(_.calitp_itp_id, _.calitp_url_number, _.agency_name)
  >> summarize(n_filled_entries = _.tts_stop_name.notna().astype(int).sum())
  >> count(_.n_filled_entries)
)

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=5000000000)
# Preview:
   n_filled_entries    n
0                 0  189
# .. may have more rows

In [40]:
stop_name_counts >> filter(_.has_stop_name)

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=5000000000)
# Preview:
Empty DataFrame
Columns: [calitp_itp_id, calitp_url_number, agency_name, has_stop_name, n]
Index: []
# .. may have more rows

## How many feeds publish wheelchair_boarding?
##For parentless stops:
0 or empty - No accessibility information for the stop.
1 - Some vehicles at this stop can be boarded by a rider in a wheelchair.
2 - Wheelchair boarding is not possible at this stop.

For child stops:
0 or empty - Stop will inherit its wheelchair_boarding behavior from the parent station, if specified in the parent.
1 - There exists some accessible path from outside the station to the specific stop/platform.
2 - There exists no accessible path from outside the station to the specific stop/platform.

For station entrances/exits:
0 or empty - Station entrance will inherit its wheelchair_boarding behavior from the parent station, if specified for the parent.
1 - Station entrance is wheelchair accessible.
2 - No accessible path from station entrance to stops/platforms.


clarify none-> rename as empty, try to clarify/research where parent station vs.

In [50]:
tbl_feed_stops >> select(_.wheelchair_boarding, _.contains(""))

,wheelchair_boarding,calitp_itp_id,calitp_url_number,stop_id,tts_stop_name,stop_lat,stop_lon,zone_id,parent_station,stop_code,...,feed_contact_url,feed_start_date,calitp_extracted_at_y,feed_publisher_name,feed_lang,default_lang,feed_version,feed_end_date,feed_contact_email,agency_name
0,0,257,0,31823,None,37.791844,-122.458726,None,None,None,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
1,0,257,0,31792,None,37.788689,-122.482329,None,None,None,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
2,0,257,0,31808,None,37.793923,-122.474462,None,None,None,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
3,0,257,0,31986,None,37.800879,-122.454381,None,None,None,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
4,0,257,0,31980,None,37.798101,-122.448203,None,None,None,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo

In [52]:
wheelchair_boarding = tbl_feed_stops >> select(_.wheelchair_boarding) >> collect()

In [56]:
wheelchair_boarding.notna().astype(int).sum()

wheelchair_boarding    732722
dtype: int64

In [66]:
(tbl_feed_stops
   >> group_by(_.calitp_itp_id, _.calitp_url_number, _.agency_name)
   >> summarize(n_wheelchair_notnull = _.wheelchair_boarding.notna().astype(int).sum())
   >> count(has_wheelchair_entry = _.n_wheelchair_notnull > 0)
)

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=5000000000)
# Preview:
   has_wheelchair_entry    n
0                  True  148
1                 False   41
# .. may have more rows

In [ ]:
SELECT 
  calitp_itp_id, calitp_url_number
  , SUM(CAST((wheelchair_boarding IS NULL OR wheelchair_boarding = "0") AS INT))
      AS n_wheelchair1
  , SUM(CAST((wheelchair_boarding IS NULL) AS INT))
      AS n_wheelchair2
FROM gtfs_schedule.stops
GROUP BY 1, 2

In [70]:
(tbl_feed_stops
   >> mutate(has_wheelchair_boarding = _.wheelchair_boarding.notna() | (_.wheelchair_boarding == "0")) 
   >> group_by(_.calitp_itp_id, _.calitp_url_number, _.agency_name)
   >> summarize(n_wheelchair_notnull = _.has_wheelchair_boarding.astype(int).sum())
   >> count(has_wheelchair_entry = _.n_wheelchair_notnull > 0)
)

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=5000000000)
# Preview:
  has_wheelchair_entry    n
0                 True  148
1                 None   41
# .. may have more rows

In [63]:
tbl_feed_stops >> count(_.calitp_itp_id, _.calitp_url_number, _.wheelchair_boarding) >> count(_.wheelchair_boarding)
#n is number of feeds where WC value of 0

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=5000000000)
# Preview:
  wheelchair_boarding    n
0                   0  141
1                None   43
2                   1   43
3                   2    9
# .. may have more rows

In [48]:
(tbl_feed_stops
 >> group_by(_.calitp_itp_id, _.calitp_url_number, _.agency_name)
 >> summarize(_.wheelchair_boarding, _.calitp_itp_id, )
)

,calitp_itp_id,calitp_url_number,stop_id,tts_stop_name,stop_lat,stop_lon,zone_id,parent_station,stop_code,stop_name,...,feed_contact_url,feed_start_date,calitp_extracted_at_y,feed_publisher_name,feed_lang,default_lang,feed_version,feed_end_date,feed_contact_email,agency_name
0,257,0,31823,None,37.791844,-122.458726,None,None,None,Inspiration Point,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
1,257,0,31792,None,37.788689,-122.482329,None,None,None,25th Ave,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
2,257,0,31808,None,37.793923,-122.474462,None,None,None,West Washington (inbound),...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
3,257,0,31986,None,37.800879,-122.454381,None,None,None,Presidio Community YMCA (inbound),...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo
4,257,0,31980,None,37.798101,-122.448203,None,None,None,Letterman Digital Arts Center,...,https://gmvsyncromatics.com/contact,20201031,2021-08-03,GMV Syncromatics,en-US,en-US,11/1/2020,None,support@gmvsync.com,PresidiGo

#need clarification on the whole parent stop thing with wheelchair

# How many feeds publish fare_leg_rules? 

#SELECT * FROM `cal-itp-data-infra-staging.gtfs_schedule_history.calitp_files_updates` WHERE name = 'fare_leg_rules.txt' ORDER BY name asc 
#answer is 11 out of 455586, or .0024%

In [30]:
tbl_file_updates = tbl.gtds_schedule_history.calitp_file_update()

AttributeError: No such attribute gtds_schedule_history

In [ ]:
tbl_feed_text = (
    tbl.gtfs_schedule_history.calitp_file_updates()
    >>summarize (
        fare_leg_rules = _.fare_lef_rules

# How many feeds publish fare_rules?
#16520 out of 455586 or 3.62%

# How many feeds publish pathways.txt?

# How many feeds publish levels.txt?
#answer is 10 out of 455586 
#.0021%

# How many Feeds publish levels.txt?
#answer is 10 out of 455586#
#.0021%#