In [1]:
import pandas as pd
import geopandas as gpd

# Agency ID - Duplicate ID Analysis

Regarding the Agency ID Reconciliation Project, agency identifier data from CTIPS, CalSMART, LP2000 and Cal-ITP were compiled in a Airtable. 
Initial data was extracted from Airtable with the following conditions.
    
1. CTIPS, CalSMART, LP2000 columns do not have duplicate IDs

However, Cal-ITP IDs do have duplicate ID values. Investigate why these duplciate values happen or where they appear.

In [6]:
ids = pd.read_csv('gs://calitp-analytics-data/data-analyses/agency_id/airtable_agency_id_2023_22_12.csv')
ids.columns

Index(['Name', 'CTIPS Agency', 'CalSMART Agency', 'LP2000 Agency',
       'Cal-ITP Organization', 'Internal_Duplicate_Check', 'Last Update',
       'Organization Type (from Cal-ITP Organization)'],
      dtype='object')

In [7]:
#checking values in these columns.
print(ids['Organization Type (from Cal-ITP Organization)'].value_counts(), #OK to drop
ids['Internal_Duplicate_Check'].value_counts(), #OK to drop
ids['Last Update'].value_counts() #OK to drop
     )

City    2
Name: Organization Type (from Cal-ITP Organization), dtype: int64 QC    1641
Name: Internal_Duplicate_Check, dtype: int64 11/9/2023 5:01am      1638
11/21/2023 12:37am       1
11/21/2023 12:35am       1
11/21/2023 12:36am       1
Name: Last Update, dtype: int64

In [8]:
#drop columns: interal duplicate check, last update, org type
ids = ids.drop(['Organization Type (from Cal-ITP Organization)',
                'Internal_Duplicate_Check',
                'Last Update'],
               axis=1)

ids

,Name,CTIPS Agency,CalSMART Agency,LP2000 Agency,Cal-ITP Organization
0,All Yellow Taxi,NaN,NaN,NaN,recZztTh2mG053QYM
1,ADARide,NaN,NaN,NaN,reczYeqvyNcm49S7Z
2,Commute.org,NaN,NaN,NaN,reczvlrgxLUDiBgAy
3,City of Willows,5062,5062,5062.0,reczUYNHfMp8ZSLhU
4,Nevada County,5917,5917,5917.0,reczUcQgqgtMpkpKC
...,...,...,...,...,...
1636,City of Palmdale,5378,5378,5378.0,NaN
1637,Alameda County Transportation Authority,6068,6068,6068.0,NaN
1638,San Bernardino Associated Governments,6053,6053,6053.0,NaN
1639,Port of Richmond,6451,6451,6451.0,NaN
1640,City of Piedmont,5156,5156,5156.0,NaN

In [10]:
# Data Cleaning
# Snake case the column names
new_col = ['name',
           'ctips_agency',
           'calsmart_agency',
           'lp2000_agency',
           'calitp_id']
ids.columns = new_col
ids

,name,ctips_agency,calsmart_agency,lp2000_agency,calitp_id
0,All Yellow Taxi,NaN,NaN,NaN,recZztTh2mG053QYM
1,ADARide,NaN,NaN,NaN,reczYeqvyNcm49S7Z
2,Commute.org,NaN,NaN,NaN,reczvlrgxLUDiBgAy
3,City of Willows,5062,5062,5062.0,reczUYNHfMp8ZSLhU
4,Nevada County,5917,5917,5917.0,reczUcQgqgtMpkpKC
...,...,...,...,...,...
1636,City of Palmdale,5378,5378,5378.0,NaN
1637,Alameda County Transportation Authority,6068,6068,6068.0,NaN
1638,San Bernardino Associated Governments,6053,6053,6053.0,NaN
1639,Port of Richmond,6451,6451,6451.0,NaN
1640,City of Piedmont,5156,5156,5156.0,NaN

In [ ]:
#group by cal itp id, count dupes?