**Delete Later**
https://github.com/cal-itp/data-analyses/issues/2028


NB to explore the payment tables in the warehouse to find `charge_status = Late`

In [1]:
import geopandas as gpd
import pandas as pd
from functools import cache
from calitp_data_analysis.gcs_geopandas import GCSGeoPandas
from calitp_data_analysis.gcs_pandas import GCSPandas
from calitp_data_analysis.sql import query_sql

@cache
def gcs_geopandas():
    return GCSGeoPandas()
    
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [3]:
fct_payments_rides_v2_list = [
# 'participant_id',
# 'micropayment_id',
# 'aggregation_id',
# 'funding_source_vault_id',
# 'customer_id',
# 'principal_customer_id',
# 'earliest_tap',
# 'bin',
# 'masked_pan',
'card_scheme',
# 'issuer',
# 'issuer_country',
'form_factor',
# 'charge_amount',
# 'refund_amount',
# 'aggregation_refund_amount',
# 'nominal_amount',
'charge_type',
# 'adjustment_id',
'adjustment_type',
# 'adjustment_time_period_type',
'adjustment_description',
# 'adjustment_amount',
# 'product_id',
'product_code',
'product_description',
'product_type',
'activation_type',
# 'route_long_name',
# 'route_short_name',
# 'agency_id',
# 'agency_name',
# 'route_id',
# 'direction',
# 'vehicle_id',
# 'littlepay_transaction_id',
# 'off_littlepay_transaction_id',
# 'device_id',
'transaction_type',
'transaction_outcome',
# 'transaction_date_time_utc',
# 'transaction_date_time_pacific',
# 'location_id',
# 'location_name',
# 'latitude',
# 'longitude',
# 'on_latitude',
# 'on_longitude',
# 'on_geography',
# 'off_device_id',
# 'off_transaction_type',
# 'off_transaction_outcome',
# 'off_transaction_date_time_utc',
# 'off_transaction_date_time_pacific',
# 'off_location_id',
# 'off_location_name',
# 'off_latitude',
# 'off_longitude',
# 'off_geography',
# 'duration',
# 'distance_meters',
# 'transaction_date_pacific',
# 'day_of_week',
# 'distance_miles',

]

In [34]:
def find_late(mart_table:str, date_column:str):
    df = query_sql(f"""
    SELECT *
    FROM mart_payments.{mart_table}
    WHERE {date_column} > "2026-04-06"
    """)
    print("length of dataframe")
    print(len(df))
    mask = df.astype(str).apply(lambda col: col.str.contains("late", case=False, na=False))
    df2 = df[mask.any(axis=1)]
    display(df2.T)

## `elavon_littlepay__daily_history_transactions_deposits_billing`

In [10]:
elavon_df = query_sql(f"""
SELECT *
FROM mart_payments.fct_payments_rides_v2
WHERE transaction_date_time_pacific > "2026-04-06"

""")

In [11]:
len(elavon_df)

83042

In [12]:

mask = elavon_df.astype(str).apply(lambda col: col.str.contains("late", case=False, na=False))
elavon_result = elavon_df[mask.any(axis=1)]

In [14]:
elavon_result.T

,41516,45492
participant_id,sacrt,sacrt
micropayment_id,328ddc08-87bb-484d-ae9e-32c4d79c4fe2,7b978111-581e-494f-91b1-58908c46b52d
aggregation_id,69c04f23-4b8b-4fba-ace0-09633496c954,054e4b98-2762-4ec4-b5f7-0c50be799bc4
funding_source_vault_id,6cd44349-ab52-42fe-ab77-27c811370067,be711a8d-1de2-4b03-b9ba-e01821d52df2
customer_id,8bcea459-7e60-4114-b74b-332b3836d436,66ae7985-d4f6-4070-97e3-77cac1ba6317
principal_customer_id,8bcea459-7e60-4114-b74b-332b3836d436,66ae7985-d4f6-4070-97e3-77cac1ba6317
earliest_tap,2026-03-16 08:06:29,2026-04-17 13:13:51
bin,41470995,65394909
masked_pan,414709******9402,653949******3888
card_scheme,VISA,DISCOVER
issuer,None,None
issuer_country,UNITED STATES,UNITED STATES
form_factor,CARD,UNKNOWN
charge_amount,2.25,2.25
refund_amount,NaN,NaN
aggregation_refund_amount,NaN,NaN
nominal_amount,2.25,2.25
charge_type,flat_fare,flat_fare
adjustment_id,None,None
adjustment_type,None,None
adjustment_time_period_type,None,None
adjustment_description,None,None
adjustment_amount,NaN,NaN
product_id,None,None
product_code,None,None
product_description,None,None
product_type,None,None
activation_type,None,None
route_long_name,None,None
route_short_name,None,None
agency_id,None,None
agency_name,None,None
route_id,E112,E111
direction,INBOUND,INBOUND
vehicle_id,822,2269
littlepay_transaction_id,3c34dde2-c5e9-436c-8624-250e27c0743d,7fb5b4cd-b5e6-4091-abcf-9eeeb74b4aba
off_littlepay_transaction_id,None,None
device_id,70017,70251
transaction_type,SINGLE,SINGLE
transaction_outcome,ALLOW,ALLOW
transaction_date_time_utc,2026-04-14T15:08:10.000Z,2026-04-17T20:13:51.000Z
transaction_date_time_pacific,2026-04-14 08:08:10,2026-04-17 13:13:51
location_id,85730,85369
location_name,BELLATERRA DR & TERRAZZO DR (NB) - 85730,FIRE POPPY DR & BELLATERRA DR (NB) - 85369
latitude,38.39844,38.398708
longitude,-121.422585,-121.43963
on_latitude,38.39844,38.398708
on_longitude,-121.422585,-121.43963
on_geography,POINT(-121.4225855 38.398439833),POINT(-121.439630167 38.398707667)
off_device_id,None,None
off_transaction_type,None,None
off_transaction_outcome,None,None
off_transaction_date_time_utc,None,None
off_transaction_date_time_pacific,NaT,NaT
off_location_id,None,None
off_location_name,None,None
off_latitude,NaN,NaN
off_longitude,NaN,NaN
off_geography,None,None
duration,NaN,NaN
distance_meters,NaN,NaN
transaction_date_pacific,2026-04-14,2026-04-17
day_of_week,3,6
distance_miles,NaN,NaN

## elavon_littlepay__transaction_reconciliation

In [33]:
find_late("elavon_littlepay__transaction_reconciliation", "elavon_transaction_date")

length of dataframe
51833

Empty DataFrame
Columns: []
Index: [littlepay_settlement_id, littlepay_aggregation_id, littlepay_retrieval_reference_number, littlepay_reference_number, littlepay_external_reference_number, littlepay_record_updated_timestamp_utc, littlepay_transaction_amount, elavon_amount, elavon_surchg_amount, elavon_convnce_amt, elavon_transaction_date, elavon_purch_id, elavon_payment_reference, elavon_settlement_date, elavon_payment_date, elavon_authorization_code, elavon_chargeback_control_no, elavon_roc_text, littlepay_participant_id, littlepay_customer_id, littlepay_funding_source_id, littlepay_acquirer, littlepay__line_number, littlepay_instance, littlepay_extract_filename, littlepay_ts, elavon_account_number, elavon_routing_number, elavon_card_type, elavon_charge_type, elavon_charge_type_description, elavon_card_plan, elavon_card_no, elavon_chk_num]

## fct_elavon__transactions
* Authorization Code = Late 3

In [22]:
find_late("fct_elavon__transactions",
          "payment_date")

                                                         103347
organization_name                                          None
organization_source_record_id                              None
littlepay_participant_id                                   None
enghouse_operator_id                                       None
end_of_month_date                                    2026-04-30
payment_reference                               610600000123010
payment_date                                         2026-04-16
account_number                                        *****3225
routing_number                                      00071000288
fund_amt                                               23352.97
batch_reference                                     17106457408
batch_type                                                    D
customer_batch_reference                            00000000232
customer_name                      ORANGE COUNTY TRANSPORTATION
merchant_number                                     08044429184
external_mid                                         8044429184
store_number                                               None
chain                                                     01781
batch_amt                                              23052.57
amount                                                      2.0
surchg_amount                                               0.0
convnce_amt                                                 0.0
card_type                                                   022
charge_type                                               14119
charge_type_description              MC INTL US STANDARD CORE 1
card_plan                                                   M/C
card_no                                        531995******7880
chk_num                                                    None
transaction_date                                     2026-04-15
settlement_date                                      2026-04-16
authorization_code                                       LATEU3
chargeback_control_no                                      None
roc_text                                                   None
trn_aci                                                    None
card_scheme_ref                                       MDSURVNN5
trn_ref_num                                         17106460779
settlement_method                                           ACH
currency_code                                               USD
cb_acq_ref_id                                              None
chgbk_rsn_code                                             None
chgbk_rsn_desc                                             None
mer_ref                                             00061091820
purch_id                                                   None
cust_cod                                                   None
trn_arn                                 55436876106171064607792
term_id                                  0075420008044429184770
ent_num                                                   34254
dt                                                   2026-05-06
execution_ts                   2026-05-06 02:00:28.127534+00:00

In [50]:

fct_elavon__transactions_df = query_sql(f"""
    SELECT DISTINCT authorization_code
    FROM mart_payments.fct_elavon__transactions
""")

In [29]:
find_late("fct_payments_adjustment_transactions",
          "payment_date")

Empty DataFrame
Columns: []
Index: [end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, payment_reference, payment_date, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, card_scheme_ref, trn_ref_num, settlement_method, currency_code, trn_arn, ent_num, dt, execution_ts]

## fct_payments_aggregations

In [30]:
find_late("fct_payments_aggregations",
          "end_of_month_date_pacific")

Empty DataFrame
Columns: []
Index: [participant_id, organization_name, organization_source_record_id, end_of_month_date_pacific, end_of_month_date_utc, aggregation_id, principal_customer_id, elavon_purch_id, elavon_settlement_date, elavon_payment_date, elavon_net_amount, elavon_sales, elavon_refunds, bin, card_scheme, has_micropayment, has_authorisation, has_settlement, has_refund, aggregation_datetime, authorisation_retrieval_reference_number, settlement_retrieval_reference_number, net_micropayment_amount_dollars, total_micropayment_nominal_amount_dollars, total_sales, total_refund_activity_amount_dollars, latest_micropayment_transaction_datetime, latest_micropayment_transaction_datetime_pacific, num_micropayments, contains_pre_settlement_refund, contains_variable_fare, contains_flat_fare, contains_pending_charge, contains_adjusted_micropayment, latest_authorisation_request_type, authorisation_transaction_amount, latest_authorisation_status, final_authorisation_has_null_status, latest_authorisation_update_datetime, settlement_contains_imputed_type, latest_settlement_update_datetime, latest_settlement_update_datetime_pacific, net_settled_amount_dollars, settlement_contains_refund, settlement_debit_amount, settlement_credit_amount, contains_nonzero_sales, aggregation_is_settled, debit_is_settled, credit_is_settled, Reconciliation_Category]

## fct_payments_authorisations

In [31]:
find_late("fct_payments_authorisations",
          "authorisation_date_time_utc")

Empty DataFrame
Columns: []
Index: [participant_id, aggregation_id, acquirer_id, organization_name, organization_source_record_id, request_type, transaction_amount, currency_code, retrieval_reference_number, littlepay_reference_number, external_reference_number, response_code, status, authorisation_date_time_utc, _line_number, instance, extract_filename, littlepay_export_ts, littlepay_export_date, ts, _key, _payments_key, _content_hash]

## fct_payments_billing_transactions

In [35]:
find_late("fct_payments_billing_transactions",
          "payment_date")

length of dataframe
1449

Empty DataFrame
Columns: []
Index: [payment_reference, payment_date, end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, settlement_method, currency_code, ent_num, dt, execution_ts]

## fct_payments_chargeback_transactions

In [36]:
find_late("fct_payments_chargeback_transactions",
          "payment_date")

length of dataframe
40

Empty DataFrame
Columns: []
Index: [end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, payment_reference, payment_date, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chargeback_control_no, roc_text, cb_acq_ref_id, chgbk_rsn_code, chgbk_rsn_desc, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, transaction_date, trn_aci, card_scheme_ref, trn_ref_num, settlement_method, currency_code, trn_arn, ent_num, dt, execution_ts]

## fct_payments_deposit_transactions   
* authorization_code = LATEU3

In [37]:
find_late("fct_payments_deposit_transactions",
          "payment_date")

length of dataframe
137706

                                                          70665
end_of_month_date                                    2026-04-30
organization_name                                          None
organization_source_record_id                              None
littlepay_participant_id                                   None
payment_reference                               610600000123010
payment_date                                         2026-04-16
fund_amt                                               23352.97
batch_reference                                     17106457408
batch_type                                                    D
customer_batch_reference                            00000000232
customer_name                      ORANGE COUNTY TRANSPORTATION
merchant_number                                     08044429184
external_mid                                         8044429184
store_number                                               None
chain                                                     01781
batch_amt                                              23052.57
amount                                                      2.0
card_type                                                   022
charge_type                                               14119
charge_type_description              MC INTL US STANDARD CORE 1
card_plan                                                   M/C
transaction_date                                     2026-04-15
settlement_date                                      2026-04-16
authorization_code                                       LATEU3
roc_text                                                   None
trn_aci                                                    None
card_scheme_ref                                       MDSURVNN5
trn_ref_num                                         17106460779
settlement_method                                           ACH
currency_code                                               USD
mer_ref                                             00061091820
purch_id                                                   None
cust_cod                                                   None
trn_arn                                 55436876106171064607792
term_id                                  0075420008044429184770
ent_num                                                   34254
dt                                                   2026-05-06
execution_ts                   2026-05-06 02:00:28.127534+00:00

## fct_payments_rides_enghouse

In [38]:
find_late("fct_payments_rides_enghouse",
          "terminal_date")

length of dataframe
2705

Empty DataFrame
Columns: []
Index: [operator_id, id, ticket_id, station_name, amount, clearing_id, reason, tap_id, ticket_type, created_dttm, line, start_station, end_station, start_dttm, end_dttm, ticket_code, additional_infos, mapping_terminal_id, mapping_merchant_id, terminal, token, masked_pan, server_date, terminal_date, tx_number, tx_status, payment_reference, terminal_spdh_code, denylist_version, currency, par, fare_mode, fare_type, fare_value, fare_description, fare_linked_id, gps_longitude, gps_latitude, gps_altitude, vehicle_public_number, vehicle_name, stop_id, stop_name, platform_id, platform_name, zone_id, zone_name, line_public_number, line_name, line_direction, trip_public_number, trip_name, service_public_number, service_name, driver_id, organization_name, organization_source_record_id, route_long_name, route_short_name, agency_id, agency_name]

## `fct_payments_rides_v2`

In [5]:
for col in col_list:
    display(
        query_sql(f"""
SELECT DISTINCT {col}
FROM mart_payments.fct_payments_rides_v2
WHERE transaction_date_time_pacific > "2026-02-06"
limit 100
""")
    )

  card_scheme
0  MASTERCARD
1        None
2        VISA
3        AMEX
4    DISCOVER

      form_factor
0            CARD
1    Unidentified
2    MOBILE-PHONE
3         UNKNOWN
4  DIGITAL-WALLET
5           WATCH
6      WRIST-WORN

                charge_type
0                 flat_fare
1    complete_variable_fare
2  incomplete_variable_fare

  adjustment_type
0            None
1      WEEKLY_CAP
2       DAILY_CAP
3      PERCENTAGE
4  TIME_BASED_CAP
5   MULTI_DAY_CAP

                             adjustment_description
0                                        Time Based
1                                        31 Day Cap
2                                   SACRT-Daily cap
3                                               $15
4                            Monthly cap170 dollars
5                                Sacramento - Davis
6                    Oakland Jack London - Martinez
7                               Discount - Medicare
8                                            Senior
9                                          Disabled
10                    Military Discount Single Ride
11                            Discount - Senior 65+
12                          Medi-Care Discount Fare
13                      Oakland Jack London - Davis
14                   Fairfield-Vacaville - Berkeley
15             Great America-Santa Clara - Berkeley
16                               Morro Bay 1-Day DS
17                  Richmond -  Oakland Jack London
18                                        7 Day Cap
19                              2 Hour Cap Discount
20                               Elk Grove Time Cap
21                            Sacramento - Richmond
22                           Daily cap11.40 dollars
23                             Senior Discount Fare
24                                         Medicare
25                            Time capping discount
26                              Elk Grove Daily Cap
27                          Sacramento - Emeryville
28                 Fairfield-Vacaville - Emeryville
29  Oakland Jack London - Great America-Santa Clara
30                              Richmond - Martinez
31                 Sacramento - Fairfield-Vacaville
32           Great America-Santa Clara - Emeryville
33                      Suisun-Fairfield - Berkeley
34                                  Morro Bay 1-Day
35                            South County 1-Day DS
36                                       2 Hour Cap
37                                      SacRT-90MIN
38                                             None
39                                 Day Cap Discount
40                                              $50
41          Suisun-Fairfield -  Oakland Jack London
42                      Courtesy Card Discount Fare
43                       SBMTD Medicare Fare 30 Day
44                           Free Fare on Earth Day
45                           Veterans Discount Fare
46                              Regional 31 Day DSS
47                     Medicare Discount Cap 90 Min
48                            Weekly Cap - Medicare
49                   Richmond - Fairfield-Vacaville
50                               7 Day Cap Discount
51             Richmond - Great America-Santa Clara
52                                       Weekly Cap
53                    Suisun-Fairfield - Emeryville
54                       Senior Discount 90 min Cap
55                               South County 1-Day
56           Sacramento - Great America-Santa Clara
57                             Daily Cap - Medicare
58                                            $5.00
59                                       Time-based
60                                        Multi Day
61                                     Time capping
62                                        Daily Cap
63                     SBMTD Senior 65+ Fare 30 Day
64                 Oakland Jack London - Emeryville
65                       SBMTD Disabled Fare 30 Day
66                                          Day Cap
67                 Sacramento - Oakland Jack London
68                                Medicare Discount
69                                          General
70                            Time Based - Medicare
71                            Great America-Fremont
72                           Monthly Cap - Medicare
73                      Senior Discount Single Ride
74                     Military Discount 90 min Cap
75                                Regional Day Pass
76                              31 Day Cap Discount
77                              Time Based - Senior
78                            Sacramento - Berkeley
79                                SLO Transit 1-Day
80        Oakland Jack London - Fairfield-Vacaville

                                       product_code
0                                        2 Hour Cap
1                                       SacRT-90MIN
2                                     Fare per ride
3                                             Daily
4                            Free Fare on Earth Day
5                                   Disabled 30 Day
6                             Weekly Cap - Medicare
7                                              None
8                    Richmond - Fairfield-Vacaville
9                                           VETDISC
10                               7 Day Cap Discount
11                                 Day Cap Discount
12          Suisun-Fairfield -  Oakland Jack London
13                              Regional 31 Day DSS
14                    Suisun-Fairfield - Emeryville
15                                       Weekly Cap
16           Sacramento - Great America-Santa Clara
17                             Daily Cap - Medicare
18                               South County 1-Day
19                                  Medicare 30 Day
20             Richmond - Great America-Santa Clara
21                                Monthly (31 days)
22                                      EG-CAP90MIN
23                                        7 Day Cap
24                              2 Hour Cap Discount
25                                           SRDISC
26                                         Medicare
27                                Senior 65+ 30 Day
28                            Time capping discount
29                            Sacramento - Richmond
30                                      EG-CAPDAILY
31                                          DISC003
32                          Sacramento - Emeryville
33                 Fairfield-Vacaville - Emeryville
34  Oakland Jack London - Great America-Santa Clara
35           Great America-Santa Clara - Emeryville
36                      Suisun-Fairfield - Berkeley
37                                  Morro Bay 1-Day
38                              Richmond - Martinez
39                            South County 1-Day DS
40                 Sacramento - Fairfield-Vacaville
41                                     Time capping
42                                        Multi Day
43                                           Weekly
44                                        Daily Cap
45                                          Day Cap
46                            Great America-Fremont
47                                          General
48                 Sacramento - Oakland Jack London
49                            Time Based - Medicare
50                                Regional Day Pass
51                 Oakland Jack London - Emeryville
52                           Monthly Cap - Medicare
53                              Time Based - Senior
54        Oakland Jack London - Fairfield-Vacaville
55                              31 Day Cap Discount
56                                SLO Transit 1-Day
57                            Sacramento - Berkeley
58                                       Time Based
59                                  SACRT-Daily cap
60                  SBCAG-MONTHLY-ONESEVENTYDOLLARS
61                               Sacramento - Davis
62                                       31 Day Cap
63                   Oakland Jack London - Martinez
64                                          DISC002
65                   SBCAG-DAILY-ELEVENFORTYDOLLARS
66                                           CCDISC
67                            Discount - Senior 65+
68                              Discount - Medicare
69                                           Senior
70                                         Disabled
71                   Fairfield-Vacaville - Berkeley
72                                          DISC001
73                          Medi-Care Discount Fare
74                               Morro Bay 1-Day DS
75                      Oakland Jack London - Davis
76                  Richmond -  Oakland Jack London
77                                           CAP003
78             Great America-Santa Clara - Berkeley

                                product_description
0                                   SACRT-Daily cap
1                                        31 Day Cap
2                                               $15
3                                        Time Based
4                            Monthly cap170 dollars
5                     Military Discount Single Ride
6                           Medi-Care Discount Fare
7                               Discount - Medicare
8                                            Senior
9                                          Disabled
10                   Fairfield-Vacaville - Berkeley
11                   Oakland Jack London - Martinez
12                               Sacramento - Davis
13                      Oakland Jack London - Davis
14                            Discount - Senior 65+
15             Great America-Santa Clara - Berkeley
16                  Richmond -  Oakland Jack London
17                               Morro Bay 1-Day DS
18                               Elk Grove Time Cap
19                                        7 Day Cap
20                              2 Hour Cap Discount
21                           Daily cap11.40 dollars
22                             Senior Discount Fare
23                                         Medicare
24                            Time capping discount
25                            Sacramento - Richmond
26                              Elk Grove Daily Cap
27  Oakland Jack London - Great America-Santa Clara
28                              Richmond - Martinez
29                          Sacramento - Emeryville
30                 Fairfield-Vacaville - Emeryville
31                                  Morro Bay 1-Day
32                      Suisun-Fairfield - Berkeley
33                            South County 1-Day DS
34                 Sacramento - Fairfield-Vacaville
35           Great America-Santa Clara - Emeryville
36                                       Time-based
37                                        Multi Day
38                                     Time capping
39                                        Daily Cap
40                            Time Based - Medicare
41                            Great America-Fremont
42                           Monthly Cap - Medicare
43                                          General
44                     SBMTD Senior 65+ Fare 30 Day
45                 Sacramento - Oakland Jack London
46                                          Day Cap
47                                            $5.00
48                      Senior Discount Single Ride
49                                Medicare Discount
50                                Regional Day Pass
51                       SBMTD Disabled Fare 30 Day
52                                SLO Transit 1-Day
53                 Oakland Jack London - Emeryville
54                     Military Discount 90 min Cap
55                              Time Based - Senior
56        Oakland Jack London - Fairfield-Vacaville
57                            Sacramento - Berkeley
58                              31 Day Cap Discount
59                                       2 Hour Cap
60                                      SacRT-90MIN
61                                              $50
62                           Free Fare on Earth Day
63                                             None
64                      Courtesy Card Discount Fare
65                           Veterans Discount Fare
66                               7 Day Cap Discount
67                            Weekly Cap - Medicare
68                               South County 1-Day
69                                 Day Cap Discount
70          Suisun-Fairfield -  Oakland Jack London
71                       Senior Discount 90 min Cap
72             Richmond - Great America-Santa Clara
73                              Regional 31 Day DSS
74                    Suisun-Fairfield - Emeryville
75                                       Weekly Cap
76           Sacramento - Great America-Santa Clara
77                             Daily Cap - Medicare
78                     Medicare Discount Cap 90 Min
79                   Richmond - Fairfield-Vacaville
80                       SBMTD Medicare Fare 30 Day

  product_type
0      CAPPING
1         None
2     DISCOUNT

           activation_type
0         CUSTOMER_DEFAULT
1                     None
2  ASSIGNED_CUSTOMERS_ONLY

  transaction_type
0               ON
1              OFF
2           SINGLE

  transaction_outcome
0               ALLOW

## fct_payments_settlements

In [39]:
find_late("fct_payments_settlements",
          "end_of_month_date_pacific")

length of dataframe
66705

Empty DataFrame
Columns: []
Index: [organization_name, organization_source_record_id, settlement_id, participant_id, aggregation_id, customer_id, funding_source_id, retrieval_reference_number, littlepay_reference_number, external_reference_number, settlement_type, record_updated_timestamp_utc, refund_id, acquirer_response_rrn, settlement_status, request_created_timestamp_utc, response_created_timestamp_utc, transaction_amount, end_of_month_date_pacific, end_of_month_date_utc, imputed_type, acquirer, _line_number, instance, extract_filename, ts, _content_hash, littlepay_export_ts, littlepay_export_date, _key, _payments_key]

## fct_payments_settlements_enghouse

In [40]:
find_late("fct_payments_settlements_enghouse",
          "end_of_month_date_pacific")

length of dataframe
8453

Empty DataFrame
Columns: []
Index: [operator_id, id, operation, terminal_id, mapping_terminal_id, mapping_merchant_id, timestamp, amount, payment_reference, spdh_response, response_type, response_message, token, issuer_response, core_response, rrn, authorization_code, par, brand, organization_name, organization_source_record_id, route_long_name, route_short_name, agency_id, agency_name, end_of_month_date_pacific, end_of_month_date_utc, _content_hash]

## v2_payments_daily_transaction_deltas

In [41]:
find_late("v2_payments_daily_transaction_deltas",
          "transaction_date")

length of dataframe
364

Empty DataFrame
Columns: []
Index: [participant_id, transaction_date, ridership_count, relative_difference]

##  v2_payments_monthly_transaction_deltas

In [42]:
find_late("v2_payments_monthly_transaction_deltas",
          "month_start")

length of dataframe
0

Empty DataFrame
Columns: []
Index: [participant_id, month_start, ridership_count, relative_difference, recency_rank]

## v2_payments_reliability_monthly_unlabeled_routes

In [43]:
find_late("v2_payments_reliability_monthly_unlabeled_routes",
          "month_start")

length of dataframe
0

Empty DataFrame
Columns: []
Index: [participant_id, month_start, n_route_z_rides, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

## v2_payments_reliability_weekly_unlabeled_route

In [44]:
find_late("v2_payments_reliability_weekly_unlabeled_routes",
          "week_start")

length of dataframe
52

Empty DataFrame
Columns: []
Index: [participant_id, week_start, n_route_z_rides, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

## v2_payments_reliability_weekly_unlabeled_routes_enghouse

In [45]:
find_late("v2_payments_reliability_weekly_unlabeled_routes_enghouse",
          "week_start")

length of dataframe
16

Empty DataFrame
Columns: []
Index: [operator_id, week_start, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

##   v2_payments_weekly_transaction_deltas

In [47]:
find_late("v2_payments_weekly_transaction_deltas",
          "week_start")

length of dataframe
52

Empty DataFrame
Columns: []
Index: [participant_id, week_start, ridership_count, relative_difference, recency_rank]