**Delete Later**
https://github.com/cal-itp/data-analyses/issues/2028


NB to explore the payment tables in the warehouse to find `charge_status = Late`

In [1]:
import geopandas as gpd
import pandas as pd
from functools import cache
from calitp_data_analysis.gcs_geopandas import GCSGeoPandas
from calitp_data_analysis.gcs_pandas import GCSPandas
from calitp_data_analysis.sql import query_sql

@cache
def gcs_geopandas():
    return GCSGeoPandas()
    
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [3]:
def find_late(mart_table:str, date_column:str):
    df = query_sql(f"""
    SELECT *
    FROM mart_payments.{mart_table}
    WHERE {date_column} > "2026-04-06"
    """)
    print("length of dataframe")
    print(len(df))
    mask = df.astype(str).apply(lambda col: col.str.contains("late", case=False, na=False))
    df2 = df[mask.any(axis=1)]
    display(df2.T)

## `elavon_littlepay__daily_history_transactions_deposits_billing`

In [4]:
elavon_df = query_sql(f"""
SELECT *
FROM mart_payments.fct_payments_rides_v2
WHERE transaction_date_time_pacific > "2026-04-06"

""")

In [5]:
len(elavon_df)

86537

In [6]:

mask = elavon_df.astype(str).apply(lambda col: col.str.contains("late", case=False, na=False))
elavon_result = elavon_df[mask.any(axis=1)]

In [7]:
elavon_result.T

,20803,49531
participant_id,sacrt,sacrt
micropayment_id,7b978111-581e-494f-91b1-58908c46b52d,328ddc08-87bb-484d-ae9e-32c4d79c4fe2
aggregation_id,054e4b98-2762-4ec4-b5f7-0c50be799bc4,69c04f23-4b8b-4fba-ace0-09633496c954
funding_source_vault_id,be711a8d-1de2-4b03-b9ba-e01821d52df2,6cd44349-ab52-42fe-ab77-27c811370067
customer_id,66ae7985-d4f6-4070-97e3-77cac1ba6317,8bcea459-7e60-4114-b74b-332b3836d436
principal_customer_id,66ae7985-d4f6-4070-97e3-77cac1ba6317,8bcea459-7e60-4114-b74b-332b3836d436
earliest_tap,2026-04-17 13:13:51,2026-03-16 08:06:29
bin,65394909,41470995
masked_pan,653949******3888,414709******9402
card_scheme,DISCOVER,VISA
issuer,None,None
issuer_country,UNITED STATES,UNITED STATES
form_factor,UNKNOWN,CARD
charge_amount,2.25,2.25
refund_amount,NaN,NaN
aggregation_refund_amount,NaN,NaN
nominal_amount,2.25,2.25
charge_type,flat_fare,flat_fare
adjustment_id,None,None
adjustment_type,None,None
adjustment_time_period_type,None,None
adjustment_description,None,None
adjustment_amount,NaN,NaN
product_id,None,None
product_code,None,None
product_description,None,None
product_type,None,None
activation_type,None,None
route_long_name,None,None
route_short_name,None,None
agency_id,None,None
agency_name,None,None
route_id,E111,E112
direction,INBOUND,INBOUND
vehicle_id,2269,822
littlepay_transaction_id,7fb5b4cd-b5e6-4091-abcf-9eeeb74b4aba,3c34dde2-c5e9-436c-8624-250e27c0743d
off_littlepay_transaction_id,None,None
device_id,70251,70017
transaction_type,SINGLE,SINGLE
transaction_outcome,ALLOW,ALLOW
transaction_date_time_utc,2026-04-17T20:13:51.000Z,2026-04-14T15:08:10.000Z
transaction_date_time_pacific,2026-04-17 13:13:51,2026-04-14 08:08:10
location_id,85369,85730
location_name,FIRE POPPY DR & BELLATERRA DR (NB) - 85369,BELLATERRA DR & TERRAZZO DR (NB) - 85730
latitude,38.398708,38.39844
longitude,-121.43963,-121.422585
on_latitude,38.398708,38.39844
on_longitude,-121.43963,-121.422585
on_geography,POINT(-121.439630167 38.398707667),POINT(-121.4225855 38.398439833)
off_device_id,None,None
off_transaction_type,None,None
off_transaction_outcome,None,None
off_transaction_date_time_utc,None,None
off_transaction_date_time_pacific,NaT,NaT
off_location_id,None,None
off_location_name,None,None
off_latitude,NaN,NaN
off_longitude,NaN,NaN
off_geography,None,None
duration,NaN,NaN
distance_meters,NaN,NaN
transaction_date_pacific,2026-04-17,2026-04-14
day_of_week,6,3
distance_miles,NaN,NaN

## elavon_littlepay__transaction_reconciliation

In [8]:
find_late("elavon_littlepay__transaction_reconciliation", "elavon_transaction_date")

length of dataframe
53183

Empty DataFrame
Columns: []
Index: [littlepay_settlement_id, littlepay_aggregation_id, littlepay_retrieval_reference_number, littlepay_reference_number, littlepay_external_reference_number, littlepay_record_updated_timestamp_utc, littlepay_transaction_amount, elavon_amount, elavon_surchg_amount, elavon_convnce_amt, elavon_transaction_date, elavon_purch_id, elavon_payment_reference, elavon_settlement_date, elavon_payment_date, elavon_authorization_code, elavon_chargeback_control_no, elavon_roc_text, littlepay_participant_id, littlepay_customer_id, littlepay_funding_source_id, littlepay_acquirer, littlepay__line_number, littlepay_instance, littlepay_extract_filename, littlepay_ts, elavon_account_number, elavon_routing_number, elavon_card_type, elavon_charge_type, elavon_charge_type_description, elavon_card_plan, elavon_card_no, elavon_chk_num]

## fct_elavon__transactions
* Authorization Code = Late 3

In [34]:
fct_elavon__transactions_df = query_sql(f"""
    SELECT *
    FROM mart_payments.fct_elavon__transactions
    WHERE payment_date > "2026-04-06"
    """)

In [35]:
fct_elavon__transactions_df2 = fct_elavon__transactions_df.loc[
    fct_elavon__transactions_df.authorization_code == "LATEU3"
]

In [36]:
fct_elavon__transactions_df2.shape

(1, 49)

In [37]:
fct_elavon__transactions_df2

,organization_name,organization_source_record_id,littlepay_participant_id,enghouse_operator_id,end_of_month_date,payment_reference,payment_date,account_number,routing_number,fund_amt,batch_reference,batch_type,customer_batch_reference,customer_name,merchant_number,external_mid,store_number,chain,batch_amt,amount,surchg_amount,convnce_amt,card_type,charge_type,charge_type_description,card_plan,card_no,chk_num,transaction_date,settlement_date,authorization_code,chargeback_control_no,roc_text,trn_aci,card_scheme_ref,trn_ref_num,settlement_method,currency_code,cb_acq_ref_id,chgbk_rsn_code,chgbk_rsn_desc,mer_ref,purch_id,cust_cod,trn_arn,term_id,ent_num,dt,execution_ts
39082,None,None,None,None,2026-04-30,610600000123010,2026-04-16,*****3225,00071000288,23352.97,17106457408,D,00000000232,ORANGE COUNTY TRANSPORTATION,08044429184,8044429184,None,01781,23052.57,2.0,0.0,0.0,022,14119,MC INTL US STANDARD CORE 1,M/C,531995******7880,None,2026-04-15,2026-04-16,LATEU3,None,None,None,MDSURVNN5,17106460779,ACH,USD,None,None,None,00061091820,None,None,55436876106171064607792,0075420008044429184770,34254,2026-05-07,2026-05-07 02:00:26.980572+00:00

In [9]:
find_late("fct_elavon__transactions",
          "payment_date")

length of dataframe
144251

                                                          39082
organization_name                                          None
organization_source_record_id                              None
littlepay_participant_id                                   None
enghouse_operator_id                                       None
end_of_month_date                                    2026-04-30
payment_reference                               610600000123010
payment_date                                         2026-04-16
account_number                                        *****3225
routing_number                                      00071000288
fund_amt                                               23352.97
batch_reference                                     17106457408
batch_type                                                    D
customer_batch_reference                            00000000232
customer_name                      ORANGE COUNTY TRANSPORTATION
merchant_number                                     08044429184
external_mid                                         8044429184
store_number                                               None
chain                                                     01781
batch_amt                                              23052.57
amount                                                      2.0
surchg_amount                                               0.0
convnce_amt                                                 0.0
card_type                                                   022
charge_type                                               14119
charge_type_description              MC INTL US STANDARD CORE 1
card_plan                                                   M/C
card_no                                        531995******7880
chk_num                                                    None
transaction_date                                     2026-04-15
settlement_date                                      2026-04-16
authorization_code                                       LATEU3
chargeback_control_no                                      None
roc_text                                                   None
trn_aci                                                    None
card_scheme_ref                                       MDSURVNN5
trn_ref_num                                         17106460779
settlement_method                                           ACH
currency_code                                               USD
cb_acq_ref_id                                              None
chgbk_rsn_code                                             None
chgbk_rsn_desc                                             None
mer_ref                                             00061091820
purch_id                                                   None
cust_cod                                                   None
trn_arn                                 55436876106171064607792
term_id                                  0075420008044429184770
ent_num                                                   34254
dt                                                   2026-05-07
execution_ts                   2026-05-07 02:00:26.980572+00:00

In [10]:

fct_elavon__transactions_df = query_sql(f"""
    SELECT DISTINCT authorization_code
    FROM mart_payments.fct_elavon__transactions
""")

In [11]:
find_late("fct_payments_adjustment_transactions",
          "payment_date")

length of dataframe
0

Empty DataFrame
Columns: []
Index: [end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, enghouse_operator_id, payment_reference, payment_date, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, card_scheme_ref, trn_ref_num, settlement_method, currency_code, trn_arn, ent_num, dt, execution_ts]

## fct_payments_aggregations

In [12]:
find_late("fct_payments_aggregations",
          "end_of_month_date_pacific")

length of dataframe
75139

Empty DataFrame
Columns: []
Index: [participant_id, organization_name, organization_source_record_id, end_of_month_date_pacific, end_of_month_date_utc, aggregation_id, principal_customer_id, elavon_purch_id, elavon_settlement_date, elavon_payment_date, elavon_net_amount, elavon_sales, elavon_refunds, bin, card_scheme, has_micropayment, has_authorisation, has_settlement, has_refund, aggregation_datetime, authorisation_retrieval_reference_number, settlement_retrieval_reference_number, net_micropayment_amount_dollars, total_micropayment_nominal_amount_dollars, total_sales, total_refund_activity_amount_dollars, latest_micropayment_transaction_datetime, latest_micropayment_transaction_datetime_pacific, num_micropayments, contains_pre_settlement_refund, contains_variable_fare, contains_flat_fare, contains_pending_charge, contains_adjusted_micropayment, latest_authorisation_request_type, authorisation_transaction_amount, latest_authorisation_status, final_authorisation_has_null_status, latest_authorisation_update_datetime, settlement_contains_imputed_type, latest_settlement_update_datetime, latest_settlement_update_datetime_pacific, net_settled_amount_dollars, settlement_contains_refund, settlement_debit_amount, settlement_credit_amount, contains_nonzero_sales, aggregation_is_settled, debit_is_settled, credit_is_settled, Reconciliation_Category]

## fct_payments_authorisations

In [13]:
find_late("fct_payments_authorisations",
          "authorisation_date_time_utc")

length of dataframe
91375

Empty DataFrame
Columns: []
Index: [participant_id, aggregation_id, acquirer_id, organization_name, organization_source_record_id, request_type, transaction_amount, currency_code, retrieval_reference_number, littlepay_reference_number, external_reference_number, response_code, status, authorisation_date_time_utc, _line_number, instance, extract_filename, littlepay_export_ts, littlepay_export_date, ts, _key, _payments_key, _content_hash]

## fct_payments_billing_transactions

In [14]:
find_late("fct_payments_billing_transactions",
          "payment_date")

length of dataframe
1449

Empty DataFrame
Columns: []
Index: [payment_reference, payment_date, end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, enghouse_operator_id, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, settlement_method, currency_code, ent_num, dt, execution_ts]

## fct_payments_chargeback_transactions

In [15]:
find_late("fct_payments_chargeback_transactions",
          "payment_date")

length of dataframe
42

Empty DataFrame
Columns: []
Index: [end_of_month_date, organization_name, organization_source_record_id, littlepay_participant_id, enghouse_operator_id, payment_reference, payment_date, fund_amt, batch_reference, batch_type, customer_name, merchant_number, external_mid, chargeback_control_no, roc_text, cb_acq_ref_id, chgbk_rsn_code, chgbk_rsn_desc, chain, batch_amt, amount, card_type, charge_type, charge_type_description, card_plan, transaction_date, trn_aci, card_scheme_ref, trn_ref_num, settlement_method, currency_code, trn_arn, ent_num, dt, execution_ts]

## fct_payments_deposit_transactions   
* authorization_code = LATEU3

In [29]:
fct_payments_deposit_transactions_df = query_sql(f"""
    SELECT *
    FROM mart_payments.fct_payments_deposit_transactions
    WHERE payment_date > "2026-04-06"
    """)

In [31]:
fct_payments_deposit_transactions_df2 = fct_payments_deposit_transactions_df.loc[
    fct_payments_deposit_transactions_df.authorization_code == "LATEU3"
]

In [32]:
fct_payments_deposit_transactions_df2.shape

(1, 39)

In [33]:
fct_payments_deposit_transactions_df2

,end_of_month_date,organization_name,organization_source_record_id,littlepay_participant_id,enghouse_operator_id,payment_reference,payment_date,fund_amt,batch_reference,batch_type,customer_batch_reference,customer_name,merchant_number,external_mid,store_number,chain,batch_amt,amount,card_type,charge_type,charge_type_description,card_plan,transaction_date,settlement_date,authorization_code,roc_text,trn_aci,card_scheme_ref,trn_ref_num,settlement_method,currency_code,mer_ref,purch_id,cust_cod,trn_arn,term_id,ent_num,dt,execution_ts
64090,2026-04-30,None,None,None,None,610600000123010,2026-04-16,23352.97,17106457408,D,00000000232,ORANGE COUNTY TRANSPORTATION,08044429184,8044429184,None,01781,23052.57,2.0,022,14119,MC INTL US STANDARD CORE 1,M/C,2026-04-15,2026-04-16,LATEU3,None,None,MDSURVNN5,17106460779,ACH,USD,00061091820,None,None,55436876106171064607792,0075420008044429184770,34254,2026-05-07,2026-05-07 02:00:26.980572+00:00

In [16]:
find_late("fct_payments_deposit_transactions",
          "payment_date")

length of dataframe
142802

                                                          64090
end_of_month_date                                    2026-04-30
organization_name                                          None
organization_source_record_id                              None
littlepay_participant_id                                   None
enghouse_operator_id                                       None
payment_reference                               610600000123010
payment_date                                         2026-04-16
fund_amt                                               23352.97
batch_reference                                     17106457408
batch_type                                                    D
customer_batch_reference                            00000000232
customer_name                      ORANGE COUNTY TRANSPORTATION
merchant_number                                     08044429184
external_mid                                         8044429184
store_number                                               None
chain                                                     01781
batch_amt                                              23052.57
amount                                                      2.0
card_type                                                   022
charge_type                                               14119
charge_type_description              MC INTL US STANDARD CORE 1
card_plan                                                   M/C
transaction_date                                     2026-04-15
settlement_date                                      2026-04-16
authorization_code                                       LATEU3
roc_text                                                   None
trn_aci                                                    None
card_scheme_ref                                       MDSURVNN5
trn_ref_num                                         17106460779
settlement_method                                           ACH
currency_code                                               USD
mer_ref                                             00061091820
purch_id                                                   None
cust_cod                                                   None
trn_arn                                 55436876106171064607792
term_id                                  0075420008044429184770
ent_num                                                   34254
dt                                                   2026-05-07
execution_ts                   2026-05-07 02:00:26.980572+00:00

## fct_payments_rides_enghouse

In [17]:
find_late("fct_payments_rides_enghouse",
          "terminal_date")

length of dataframe
2852

Empty DataFrame
Columns: []
Index: [operator_id, id, ticket_id, station_name, amount, clearing_id, reason, tap_id, ticket_type, created_dttm, line, start_station, end_station, start_dttm, end_dttm, ticket_code, additional_infos, mapping_terminal_id, mapping_merchant_id, terminal, token, masked_pan, server_date, terminal_date, tx_number, tx_status, payment_reference, terminal_spdh_code, denylist_version, currency, par, fare_mode, fare_type, fare_value, fare_description, fare_linked_id, gps_longitude, gps_latitude, gps_altitude, vehicle_public_number, vehicle_name, stop_id, stop_name, platform_id, platform_name, zone_id, zone_name, line_public_number, line_name, line_direction, trip_public_number, trip_name, service_public_number, service_name, driver_id, organization_name, organization_source_record_id, route_long_name, route_short_name, agency_id, agency_name]

## `fct_payments_rides_v2`

In [19]:
find_late("fct_payments_rides_v2",
          "transaction_date_time_pacific")

length of dataframe
86537

,28893,55697
participant_id,sacrt,sacrt
micropayment_id,328ddc08-87bb-484d-ae9e-32c4d79c4fe2,7b978111-581e-494f-91b1-58908c46b52d
aggregation_id,69c04f23-4b8b-4fba-ace0-09633496c954,054e4b98-2762-4ec4-b5f7-0c50be799bc4
funding_source_vault_id,6cd44349-ab52-42fe-ab77-27c811370067,be711a8d-1de2-4b03-b9ba-e01821d52df2
customer_id,8bcea459-7e60-4114-b74b-332b3836d436,66ae7985-d4f6-4070-97e3-77cac1ba6317
principal_customer_id,8bcea459-7e60-4114-b74b-332b3836d436,66ae7985-d4f6-4070-97e3-77cac1ba6317
earliest_tap,2026-03-16 08:06:29,2026-04-17 13:13:51
bin,41470995,65394909
masked_pan,414709******9402,653949******3888
card_scheme,VISA,DISCOVER
issuer,None,None
issuer_country,UNITED STATES,UNITED STATES
form_factor,CARD,UNKNOWN
charge_amount,2.25,2.25
refund_amount,NaN,NaN
aggregation_refund_amount,NaN,NaN
nominal_amount,2.25,2.25
charge_type,flat_fare,flat_fare
adjustment_id,None,None
adjustment_type,None,None
adjustment_time_period_type,None,None
adjustment_description,None,None
adjustment_amount,NaN,NaN
product_id,None,None
product_code,None,None
product_description,None,None
product_type,None,None
activation_type,None,None
route_long_name,None,None
route_short_name,None,None
agency_id,None,None
agency_name,None,None
route_id,E112,E111
direction,INBOUND,INBOUND
vehicle_id,822,2269
littlepay_transaction_id,3c34dde2-c5e9-436c-8624-250e27c0743d,7fb5b4cd-b5e6-4091-abcf-9eeeb74b4aba
off_littlepay_transaction_id,None,None
device_id,70017,70251
transaction_type,SINGLE,SINGLE
transaction_outcome,ALLOW,ALLOW
transaction_date_time_utc,2026-04-14T15:08:10.000Z,2026-04-17T20:13:51.000Z
transaction_date_time_pacific,2026-04-14 08:08:10,2026-04-17 13:13:51
location_id,85730,85369
location_name,BELLATERRA DR & TERRAZZO DR (NB) - 85730,FIRE POPPY DR & BELLATERRA DR (NB) - 85369
latitude,38.39844,38.398708
longitude,-121.422585,-121.43963
on_latitude,38.39844,38.398708
on_longitude,-121.422585,-121.43963
on_geography,POINT(-121.4225855 38.398439833),POINT(-121.439630167 38.398707667)
off_device_id,None,None
off_transaction_type,None,None
off_transaction_outcome,None,None
off_transaction_date_time_utc,None,None
off_transaction_date_time_pacific,NaT,NaT
off_location_id,None,None
off_location_name,None,None
off_latitude,NaN,NaN
off_longitude,NaN,NaN
off_geography,None,None
duration,NaN,NaN
distance_meters,NaN,NaN
transaction_date_pacific,2026-04-14,2026-04-17
day_of_week,3,6
distance_miles,NaN,NaN

## fct_payments_settlements

In [20]:
find_late("fct_payments_settlements",
          "end_of_month_date_pacific")

length of dataframe
69118

Empty DataFrame
Columns: []
Index: [organization_name, organization_source_record_id, settlement_id, participant_id, aggregation_id, customer_id, funding_source_id, retrieval_reference_number, littlepay_reference_number, external_reference_number, settlement_type, record_updated_timestamp_utc, refund_id, acquirer_response_rrn, settlement_status, request_created_timestamp_utc, response_created_timestamp_utc, transaction_amount, end_of_month_date_pacific, end_of_month_date_utc, imputed_type, acquirer, _line_number, instance, extract_filename, ts, _content_hash, littlepay_export_ts, littlepay_export_date, _key, _payments_key]

## fct_payments_settlements_enghouse

In [21]:
find_late("fct_payments_settlements_enghouse",
          "end_of_month_date_pacific")

length of dataframe
8823

Empty DataFrame
Columns: []
Index: [operator_id, id, operation, terminal_id, mapping_terminal_id, mapping_merchant_id, timestamp, amount, payment_reference, spdh_response, response_type, response_message, token, issuer_response, core_response, rrn, authorization_code, par, brand, organization_name, organization_source_record_id, route_long_name, route_short_name, agency_id, agency_name, end_of_month_date_pacific, end_of_month_date_utc, _content_hash]

## v2_payments_daily_transaction_deltas

In [22]:
find_late("v2_payments_daily_transaction_deltas",
          "transaction_date")

length of dataframe
377

Empty DataFrame
Columns: []
Index: [participant_id, transaction_date, ridership_count, relative_difference]

##  v2_payments_monthly_transaction_deltas

In [23]:
find_late("v2_payments_monthly_transaction_deltas",
          "month_start")

length of dataframe
0

Empty DataFrame
Columns: []
Index: [participant_id, month_start, ridership_count, relative_difference, recency_rank]

## v2_payments_reliability_monthly_unlabeled_routes

In [24]:
find_late("v2_payments_reliability_monthly_unlabeled_routes",
          "month_start")

length of dataframe
0

Empty DataFrame
Columns: []
Index: [participant_id, month_start, n_route_z_rides, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

## v2_payments_reliability_weekly_unlabeled_route

In [25]:
find_late("v2_payments_reliability_weekly_unlabeled_routes",
          "week_start")

length of dataframe
52

Empty DataFrame
Columns: []
Index: [participant_id, week_start, n_route_z_rides, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

## v2_payments_reliability_weekly_unlabeled_routes_enghouse

In [26]:
find_late("v2_payments_reliability_weekly_unlabeled_routes_enghouse",
          "week_start")

length of dataframe
16

Empty DataFrame
Columns: []
Index: [operator_id, week_start, n_null_rides, total_unlabeled_rides, n_empty_string_rides, n_all_rides, pct_unlabeled_rides_to_total_rides, recency_rank]

##   v2_payments_weekly_transaction_deltas

In [27]:
find_late("v2_payments_weekly_transaction_deltas",
          "week_start")

length of dataframe
52

Empty DataFrame
Columns: []
Index: [participant_id, week_start, ridership_count, relative_difference, recency_rank]

## Little Pay Table

In [55]:
def find_late_littlepay(mart_table:str):
    print(f"{mart_table} Table")
    df = query_sql(f"""
    SELECT *
    FROM external_littlepay.{mart_table}
    """)
    print("length of dataframe")
    print(len(df))
    mask = df.astype(str).apply(lambda col: col.str.contains("late", case=False, na=False))
    df2 = df[mask.any(axis=1)]
    display(df2.T)

In [52]:
find_late_littlepay("authorisations")

authorisations Table
length of dataframe
1209530

Empty DataFrame
Columns: []
Index: [participant_id, aggregation_id, acquirer_id, request_type, transaction_amount, currency_code, retrieval_reference_number, littlepay_reference_number, external_reference_number, response_code, status, authorisation_date_time_utc, _line_number, instance, extract_filename, ts]

In [53]:
find_late_littlepay("device_transaction_purchases ")

device_transaction_purchases  Table
length of dataframe
1267154

Empty DataFrame
Columns: []
Index: [littlepay_transaction_id, purchase_id, correlated_purchase_id, product_id, description, indicative_amount, transaction_time, _line_number, instance, extract_filename, ts]

In [56]:
find_late_littlepay("device_transactions")

device_transactions Table
length of dataframe
1263286

Empty DataFrame
Columns: []
Index: [participant_id, customer_id, device_transaction_id, littlepay_transaction_id, device_id, device_id_issuer, type, transaction_outcome, transaction_deny_reason, transaction_date_time_utc, location_id, location_scheme, location_name, zone_id, route_id, mode, direction, latitude, longitude, vehicle_id, granted_zone_ids, onward_zone_ids, processed_timestamp_utc, _line_number, instance, extract_filename, ts]

In [58]:
find_late_littlepay("micropayment_adjustments")

micropayment_adjustments Table
length of dataframe
3477913

Empty DataFrame
Columns: []
Index: [micropayment_id, adjustment_id, participant_id, customer_id, product_id, type, description, amount, time_period_type, applied, zone_ids_used, incentive_product_id, _line_number, instance, extract_filename, ts]