In [1]:
import os
os.environ["CALITP_BQ_MAX_BYTES"] = str(800_000_000_000) ## 800GB?

from calitp.tables import tbl
# from calitp import query_sql
import calitp.magics

import shared_utils
# import utils

from siuba import *
import pandas as pd
import geopandas as gpd
# import shapely

import datetime as dt
import time
# from zoneinfo import ZoneInfo

# import gcsfs
# fs = gcsfs.GCSFileSystem()

from tqdm import tqdm_notebook
from tqdm.notebook import trange, tqdm

/opt/conda/lib/python3.10/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

# Prioritizing Notices -- which should we provide guidance for first?

In [2]:
tbl.views.validation_fact_daily_feed_notices() >> head(3)

,feed_key,date,validation_created_at,validation_deleted_at,calitp_itp_id,calitp_url_number,code,severity,csvRowNumber,oldCsvRowNumber,...,routeLongName,routeDesc,stopId,stopName,serviceIdA,serviceIdB,departureTime,arrivalTime,parentStation,parentStopName
0,-3540410672069212686,2022-04-28,2022-04-28,2022-04-29,105,0,same_name_and_description_for_route,ERROR,11,None,...,None,Route 12,None,None,None,None,None,None,None,None
1,1273942275370395959,2022-06-02,2022-06-02,2022-06-03,231,0,same_name_and_description_for_route,ERROR,32,None,...,None,60-Hwy126,None,None,None,None,None,None,None,None
2,4493221564916387693,2022-05-03,2022-05-03,2022-05-04,361,0,same_name_and_description_for_route,ERROR,4,None,...,None,Route 2,None,None,None,None,None,None,None,None

In [3]:
tbl.views.validation_fact_daily_feed_codes() >> head(3)

,feed_key,code,date,n_notices,diff_n_notices,is_error_resolved,is_error_introduced
0,2590856768872525679,empty_file,2021-12-19,3,NaN,False,True
1,-5246656847780582136,invalid_url,2022-02-04,3,0.0,False,False
2,-5246656847780582136,invalid_url,2022-01-21,3,0.0,False,False

In [6]:
code_rankings = (tbl.views.validation_fact_daily_feed_codes()
     >> filter(_.date == '2022-06-01')
     >> filter(_.n_notices > 0)
     >> count(_.code)
    ) >> collect()

In [7]:
code_rankings

                                                 code    n
0                                        unknown_file  181
1                                      unknown_column  134
2                                duplicate_route_name   48
3                  decreasing_or_equal_shape_distance   47
4                                feed_expiration_date   46
5                                     too_fast_travel   34
6                        stop_too_far_from_trip_shape   23
7                     leading_or_trailing_whitespaces   22
8                                        unused_shape   21
9                           route_short_name_too_long   20
10                 duplicate_fare_rule_zone_id_fields   19
11                  stop_time_timepoint_without_times   18
12                               route_color_contrast   17
13             decreasing_or_equal_stop_time_distance   14
14                             missing_feed_info_date   12
15                    route_short_and_long_name_equal    9
16                same_name_and_description_for_route    9
17                               invalid_phone_number    5
18                                        invalid_url    2
19                             missing_required_field    2
20            block_trips_with_overlapping_stop_times    2
21                               more_than_one_entity    2
22                                      duplicate_key    1
23                                      unusable_trip    1
24  stop_time_with_arrival_before_previous_departu...    1
25                            missing_required_column    1
26                    platform_without_parent_station    1
27                         wrong_parent_location_type    1

## duplicate_route_name

In [8]:
dup_routes = (tbl.views.validation_fact_daily_feed_notices()
     >> filter(_.date == '2022-06-01')
     >> filter(_.code == 'duplicate_route_name')
    ) >> collect()

In [10]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(dup_routes >> head(10))

,feed_key,date,validation_created_at,validation_deleted_at,calitp_itp_id,calitp_url_number,code,severity,csvRowNumber,oldCsvRowNumber,newCsvRowNumber,csvRowNumberA,csvRowNumberB,rowLength,headerCount,previousCsvRowNumber,filename,fieldName,fieldName1,fieldName2,fieldValue,fieldValue1,fieldValue2,index,shapeDistTraveled,shapePtSequence,prevCsvRowNumber,prevShapeDistTraveled,prevShapePtSequence,duplicatedField,suggestedExpirationDate,suggestedExpirationDate.localDate,suggestedExpirationDate.localDate.year,suggestedExpirationDate.localDate.month,suggestedExpirationDate.localDate.day,stopSequence,specifiedField,prevStopTimeDistTraveled,prevStopSequence,speedkmh,firstStopSequence,lastStopSequence,stopShapeThresholdMeters,blockId,intersection,expectedLocationType,locationType,parentCsvRowNumber,parentLocationType,entityCount,fieldType,childFieldName,parentFieldName,childFilename,parentFilename,fareId,previousFareId,shapeId,routeId,currentDate,feedEndDate,routeColor,routeTextColor,tripId,tripIdA,tripIdB,routeShortName,routeLongName,routeDesc,stopId,stopName,serviceIdA,serviceIdB,departureTime,arrivalTime,parentStation,parentStopName
0,-3696369716674726447,2022-06-01,2022-06-01,2022-06-02,232,0,duplicate_route_name,WARNING,45,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,10422,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,76,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,237-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,38,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,125-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,14-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,41,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,130-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,-5693386325383800078,2022-06-01,2022-06-01,2022-06-02,239,0,duplicate_route_name,WARNING,8,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_short_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,746,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
6,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,78,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,242-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
7,-2909967723991199002,2022-06-01,2022-06-01,2022-06-02,293,0,duplicate_route_name,WARNING,24,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2620,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
8,-6529403417725531963,2022-06-01,2022-06-01,2022-06-02,360,1,duplicate_route_name,WARNING,35,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,19745,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
9,4164903538710312962,2022-06-01,2022-06-01,2022-06-02,182,0,duplicate_route_name,WARNING,13,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,route_long_name,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,40-13159,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [28]:
dup_routes >> filter(_.calitp_itp_id != 182) >> count(_.calitp_itp_id, _.calitp_url_number) >> arrange(-_.n)

    calitp_itp_id  calitp_url_number   n
26            232                  0  53
7              61                  0  43
23            200                  0  18
46            482                  0  17
33            293                  0  14
35            295                  0  10
43            360                  1  10
15            142                  0   9
27            235                  0   9
18            167                  1   5
8              70                  0   3
19            170                  0   3
22            199                  0   3
37            314                  0   3
38            314                  1   3
2              11                  0   2
6              50                  0   2
20            194                  0   2
21            194                  1   2
24            217                  1   2
32            284                  0   2
34            294                  1   2
42            336                  0   2
44            376                  0   2
0               4                  0   1
1               4                  1   1
3              14                  0   1
4              18                  0   1
5              42                  0   1
9             108                  0   1
10            120                  0   1
11            126                  0   1
12            127                  0   1
13            127                  1   1
14            135                  0   1
16            165                  0   1
17            167                  0   1
25            226                  0   1
28            239                  0   1
29            246                  0   1
30            246                  1   1
31            273                  0   1
36            301                  0   1
39            324                  0   1
40            329                  0   1
41            334                  0   1
45            380                  0   1

In [13]:
routes_on_date = tbl.views.gtfs_schedule_fact_daily_feed_routes() >> filter(_.date == '2022-06-01')

In [16]:
tbl_routes = tbl.views.gtfs_schedule_dim_routes() >> inner_join(_, routes_on_date, on = 'route_key')

In [29]:
def show_rt_counts(itp_id, url_number):
    tbl_routes = tbl.views.gtfs_schedule_dim_routes() >> inner_join(_, routes_on_date, on = 'route_key')
    this_feed = tbl_routes >> filter(_.calitp_itp_id == itp_id, _.calitp_url_number == url_number)
    print('count of short names:')
    display(this_feed >> count(_.route_short_name) >> arrange(-_.n))
    print('count of long names:')
    display(this_feed >> count(_.route_long_name) >> arrange(-_.n))
    return

In [30]:
show_rt_counts(61, 0)

count of short names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
  route_short_name  n
0               16  2
1               21  2
2                9  2
3              99X  2
4               11  2
# .. may have more rows

count of long names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
                   route_long_name  n
0   Concord BART/Walnut Creek BART  2
1  Concord BART/Pleasant Hill BART  2
2     Martinez Amtrak/Concord BART  2
3                 DVC/Concord BART  2
4      Walnut Creek BART/San Ramon  2
# .. may have more rows

In [31]:
show_rt_counts(482, 0)

count of short names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
  route_short_name  n
0            Rte 2  4
1            Rte 3  3
2              ADV  3
3             PINE  3
4            Rte 5  2
# .. may have more rows

count of long names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
                 route_long_name  n
0              Adventure Trolley  3
1                      Pinecrest  3
2    Route 2 - To Sierra Village  2
3  Route 3 - To Sonora-Jamestown  1
4            Route 2 - To Sonora  1
# .. may have more rows

In [32]:
show_rt_counts(182, 0)

count of short names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
                   route_short_name  n
0                              None  3
1                               246  1
2  South Bay Dodger Stadium Express  1
3                                33  1
4                               154  1
# .. may have more rows

count of long names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
                 route_long_name    n
0               Metro Local Line  100
1             Metro Express Line    6
2               Metro Rapid Line    3
3                           None    2
4  Metro J Line (Silver) 910/950    1
# .. may have more rows

In [33]:
show_rt_counts(293, 0)

count of short names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
  route_short_name  n
0              24X  1
1                3  1
2             2530  1
3             2410  1
4             2430  1
# .. may have more rows

count of long names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
           route_long_name  n
0   Goleta Valley Jr. High  5
1  Dos Pueblos High School  5
2   San Marcos High School  4
3       La Colina Jr. High  4
4           Goleta Express  1
# .. may have more rows

In [34]:
show_rt_counts(295, 0)

count of short names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
  route_short_name  n
0               12  1
1              101  1
2              102  1
3              622  1
4              200  1
# .. may have more rows

count of long names:

# Source: lazy query
# DB Conn: Engine(bigquery://cal-itp-data-infra/?maximum_bytes_billed=800000000000)
# Preview:
      route_long_name  n
0     La Mesa Jr High  4
1         Saugus High  3
2  Golden Valley High  3
3        Century City  2
4       Warner Center  2
# .. may have more rows