# Run Functions to Add Information to Projects

To run the data through the script, all you need to do is update `my_file` path to the most recent export from FMIS and QMRS uploaded to GCS, then run the function in the section `Export Data` with your dataframe and the current date. Then your aggregated data will be ready in GCS.

In [1]:
import _data_utils
import _script_utils
import pandas as pd
from calitp_data_analysis.sql import to_snakecase

In [2]:
from calitp_data_analysis.gcs_geopandas import GCSGeoPandas
gcsgp = GCSGeoPandas()

In [3]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", None)

In [4]:
locodes = to_snakecase(
    pd.read_excel(
        f"gs://calitp-analytics-data/data-analyses/dla/e-76Obligated/locodes_updated7122021.xlsx"
    )
)

## Read in Data and function development / Test Function

For the following function:
* update the file path for `my_file` to the most recent file name of the FMIS & QMRS export
* the second kwargs is the unique recipient identifier, in this case it should stay the same with subsequent exports
* the third kwargs is the aggregation level you want for the data. Unless otherwise specified, it should be `agg` which is one row per project

In [5]:
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/dla/dla-iija"

In [6]:
# update this path to the latest IIJA data
my_file = "IIJA_ToDDS_20260623.xlsx"

### Check data
* July 2025 Notes
    * `summary_recipient_defined_text_field_1_value` changed to `summary_recipient` in `script_utils.run_script_original` and `script_utils.run_script_2025.`
    * `rk_locode` is missing so I used `run_script_original` instead.
    * Updated `_script_utils.add_county_abbrev()` because the values in the counties geojson in `shared_data_catalog.yml` changed.

In [8]:
check_data = to_snakecase(pd.read_excel(f"{GCS_FILE_PATH}/{my_file}", sheet_name="Sheet1"))

In [9]:
check_data.columns

Index(['fmis_transaction_date', 'program_code', 'unnamed:_2',
       'program_code_description', 'project_number',
       'recipient_project_number', '_10_id', 'project_title', 'county_code',
       'unnamed:_9', 'congressional_district', 'project_status_description',
       'project_description', 'improvement_type',
       'improvement_type_description', 'total_cost_amount',
       'obligations_amount', 'summary_recipient_defined_text_field_1_value'],
      dtype='object')

In [10]:
check_data.head(1)

,fmis_transaction_date,program_code,unnamed:_2,program_code_description,project_number,recipient_project_number,_10_id,project_title,county_code,unnamed:_9,congressional_district,project_status_description,project_description,improvement_type,improvement_type_description,total_cost_amount,obligations_amount,summary_recipient_defined_text_field_1_value
0,2022-10-27,YS30,NaN,SURFAC TRNSP BLK GRTS-FLX IIJA,Q101398,0100000193S,0100000193,IN DEL NORTE COUNTY NEAR CRESCENT CITY FROM 0.3 MILE SOUTH OF SMITH RIVER BRIDGE TO 0.4 MILE NORTH OF SMITH RIVER BRIDGE REPLACE BRIDGE,15,NaN,Cong Dist 1,Active,"SIXTEEN STOP-CONTROLLED INTERSECTIONS AT VARIOUS LOCATIONS SYSTEMICALLY IMPROVE MINOR STREET APPROACHES WITH A COMBINATION OF ADDITIONAL INTERSECTION WARNING/REGULATORY SIGNS, IMPROVED PAVEMENT MARKINGS, AND IMPROVED SIGHT TRIANGLES.",4,4R - No Added Capacity,366560.0,329904.0,L5425BCAG

### Run Script
* Choose between `run_script_original` or `run_script_2025` depending on the dataframe you receive.

In [48]:
df = _script_utils.run_script_original(
    file_name = my_file, 
    sheet = "Sheet1",
    recipient_column = "summary_recipient_defined_text_field_1_value", 
    df_agg_level = "agg"
)

Index(['fmis_transaction_date', 'project_number', 'implementing_agency',
       'summary_recipient_defined_text_field_1_value', 'funding_type_code',
       'program_code', 'program_code_description', 'recipient_project_number',
       'improvement_type', 'improvement_type_description',
       'program_code_description_for_description', 'project_title',
       'obligations_amount', 'total_cost_amount', 'congressional_district',
       'district', 'county_code', 'county_name', 'county_name_abbrev',
       'county_name_title', 'implementing_agency_locode', 'rtpa_name',
       'mpo_name'],
      dtype='object')

False

### Compare with January 2026

In [34]:
jan_2026 = to_snakecase(pd.read_excel("gs://calitp-analytics-data/data-analyses/dla/dla-iija/IIJA_ToDDS_20260113.xlsx"))

In [35]:
jan_2026_agg = _script_utils.run_script_original(
    file_name = "IIJA_ToDDS_20260113.xlsx", 
    sheet = "IIJA_ToDDS",
    recipient_column = "summary_recipient_defined_text_field_1_value", 
    df_agg_level = "agg"
)

Index(['fmis_transaction_date', 'project_number', 'implementing_agency',
       'summary_recipient_defined_text_field_1_value', 'funding_type_code',
       'program_code', 'program_code_description', 'recipient_project_number',
       'improvement_type', 'improvement_type_description',
       'program_code_description_for_description', 'project_title',
       'obligations_amount', 'total_cost_amount', 'congressional_district',
       'district', 'county_code', 'county_name', 'county_name_abbrev',
       'county_name_title', 'implementing_agency_locode', 'rtpa_name',
       'mpo_name'],
      dtype='object')

True

In [42]:
jan_2026.project_number.value_counts().head(700)

project_number
5006912    34
P134040    20
6049028    18
0056349    18
6049030    17
           ..
S198077     3
X029141     3
0055159     3
S033093     3
0054206     3
Name: count, Length: 700, dtype: int64

In [43]:
jan_2026.loc[jan_2026.project_number == "S033093"]

,fmis_transaction_date,program_code,program_code_description,project_number,recipient_project_number,_10_id,project_title,county_code,congressional_district,project_status_description,project_description,improvement_type,improvement_type_description,total_cost_amount,obligations_amount,summary_recipient_defined_text_field_1_value
4048,2024-05-02,Y240,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,Cong Dist 13,Active,ON STATE ROUTE: 33. IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),6,4R - Restoration & Rehabilitation,15892300.0,13896100.0,S FCOG
4049,2024-05-02,Y240,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,Cong Dist 13,Active,ON STATE ROUTE: 33. IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),17,Construction Engineering,2800000.0,2478800.0,S FCOG
4050,2024-05-02,Y240,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,Cong Dist 13,Active,ON STATE ROUTE: 33. IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),42,Training,1800.0,1500.0,S FCOG

### Testing the data

In [13]:
len(df) == check_data.project_number.nunique()

False

In [14]:
len(df)

5331

In [15]:
check_data.project_number.nunique()

3451

In [44]:
check_data.project_number.value_counts().head(600)

project_number
5006912    34
P134040    20
6049028    18
0056349    18
6049032    17
           ..
P170006     3
P099659     3
0804339     3
P162045     3
P020204     3
Name: count, Length: 600, dtype: int64

In [16]:
check_data.columns

Index(['fmis_transaction_date', 'program_code', 'unnamed:_2',
       'program_code_description', 'project_number',
       'recipient_project_number', '_10_id', 'project_title', 'county_code',
       'unnamed:_9', 'congressional_district', 'project_status_description',
       'project_description', 'improvement_type',
       'improvement_type_description', 'total_cost_amount',
       'obligations_amount', 'summary_recipient_defined_text_field_1_value'],
      dtype='object')

In [52]:
check_data.loc[check_data.project_number == "S033093"]

,fmis_transaction_date,program_code,unnamed:_2,program_code_description,project_number,recipient_project_number,_10_id,project_title,county_code,unnamed:_9,congressional_district,project_status_description,project_description,improvement_type,improvement_type_description,total_cost_amount,obligations_amount,summary_recipient_defined_text_field_1_value
4364,2025-08-15,Y400,NaN,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,NaN,Cong Dist 38,Active,"LOS ANGELES COUNTY MOBILITY WALLETS L.A. COUNTYWIDE. FUND AND DISTRIBUTE 5,000+ WALLETS, PREPAID DEBIT CARDS WITH SUBSIDIES FOR TRANSPORTATION OPTIONS. USABLE FOR PUBLIC TRANSIT, INCLUDING BUSES, TRAINS, AND METRO MICRO VANS, TOLL LANE FEES FOR CARPOOLERS, REGIONAL TRANSIT LIKE METROLINK AND AMTRAK, PRIVATE BUSES LIKE GREYHOUND AND FLIXBUS, AND EV CAR SHARES LIKE BLUELA, RIDE-HAILING/TAXI, SHARED SCOOTERS AND BIKES, AND AT BIKE SHOPS FOR SERVICES AND PRODUCTS. TC",23,Transit,500000.0,500000.0,L6065SCAG
4365,2025-08-15,Y400,NaN,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,NaN,Cong Dist 42,Active,"LOS ANGELES COUNTY MOBILITY WALLETS L.A. COUNTYWIDE. FUND AND DISTRIBUTE 5,000+ WALLETS, PREPAID DEBIT CARDS WITH SUBSIDIES FOR TRANSPORTATION OPTIONS. USABLE FOR PUBLIC TRANSIT, INCLUDING BUSES, TRAINS, AND METRO MICRO VANS, TOLL LANE FEES FOR CARPOOLERS, REGIONAL TRANSIT LIKE METROLINK AND AMTRAK, PRIVATE BUSES LIKE GREYHOUND AND FLIXBUS, AND EV CAR SHARES LIKE BLUELA, RIDE-HAILING/TAXI, SHARED SCOOTERS AND BIKES, AND AT BIKE SHOPS FOR SERVICES AND PRODUCTS. TC",23,Transit,500000.0,500000.0,L6065SCAG
4366,2025-08-15,Y400,NaN,SURFAC TRNSP BLK GRTS-FLX IIJA,S033093,0618000051S,0618000051,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),19,NaN,Cong Dist 43,Active,"LOS ANGELES COUNTY MOBILITY WALLETS L.A. COUNTYWIDE. FUND AND DISTRIBUTE 5,000+ WALLETS, PREPAID DEBIT CARDS WITH SUBSIDIES FOR TRANSPORTATION OPTIONS. USABLE FOR PUBLIC TRANSIT, INCLUDING BUSES, TRAINS, AND METRO MICRO VANS, TOLL LANE FEES FOR CARPOOLERS, REGIONAL TRANSIT LIKE METROLINK AND AMTRAK, PRIVATE BUSES LIKE GREYHOUND AND FLIXBUS, AND EV CAR SHARES LIKE BLUELA, RIDE-HAILING/TAXI, SHARED SCOOTERS AND BIKES, AND AT BIKE SHOPS FOR SERVICES AND PRODUCTS. TC",23,Transit,500000.0,500000.0,L6065SCAG

In [53]:
df.loc[df.project_number == "S033093"]

,fmis_transaction_date,project_number,implementing_agency,summary_recipient_defined_text_field_1_value,funding_type_code,program_code,program_code_description,recipient_project_number,improvement_type,improvement_type_description,old_project_title_desc,obligations_amount,total_cost_amount,congressional_district,district,county_code,county_name,county_name_abbrev,implementing_agency_locode,rtpa_name,mpo_name,new_project_title,new_description_col
2865,2025-08-15,S033093,Los Angeles County Metropolitan Transportation Authority,L6065SCAG,IIJA-F,Y400,Congestion Mitigation & Air Quality Improvement Program,0618000051S,23,Transit,IN AND NEAR FIREBAUGH FROM MORRIS KYLE DRIVE TO 0.6 MI NORTH OF CLYDE FANNON DRIVE ROADWAY REHABILITATION (3R),3000000,3000000,|38|42|43|,|07|,19,Los Angeles County,|LA|,6065,Los Angeles County Metropolitan Transportation Auth.,Southern California Association Of Governments,Road Rehabiliation in the Los Angeles County Metropolitan Transportation Authority Region,"Road Rehabiliation in the Los Angeles County Metropolitan Transportation Authority Region, part of the Congestion Mitigation & Air Quality Improvement Program. (Federal Project ID: S033093)."

In [ ]:
df.loc[df.project_number == "S033093"]

## Export Data

In [20]:
### rename the file for export to GCS
### use date to rename

In [21]:
_script_utils.export_to_gcs(df, "01142026_agg")

## Comparing latest cleaned data with older version

In [22]:
jan_2026 = "gs://calitp-analytics-data/data-analyses/dla/dla-iija/FMIS_Projects_Universe_IIJA_Reporting_01142026_agg.csv"

In [23]:
jan_df = pd.read_csv(jan_2026)

In [24]:
len(jan_df)

5331

In [25]:
jan_df.head(1)

,Unnamed: 0,Fmis Transaction Date,Project Number,Implementing Agency,Summary Recipient Defined Text Field 1 Value,Funding Type Code,Program Code,Program Code Description,Recipient Project Number,Improvement Type,Improvement Type Description,Old Project Title Desc,Obligations Amount,Total Cost Amount,Congressional District,District,County Code,County Name,County Name Abbrev,Implementing Agency Locode,Rtpa Name,Mpo Name,New Project Title,New Description Col
0,0,2022-10-27,Q101398,Paradise,L5425BCAG,IIJA-F,YS30,Highway Safety Improvement Program (HSIP),0100000193S,4|17,4R - No Added Capacity|Construction Engineering,IN DEL NORTE COUNTY NEAR CRESCENT CITY FROM 0.3 MILE SOUTH OF SMITH RIVER BRIDGE TO 0.4 MILE NORTH OF SMITH RIVER BRIDGE REPLACE BRIDGE,379389,421544,|01|,|03|,15,Butte County,|BUT|,5425.0,Butte County Association of Governments,Butte County Association Of Governments,Replace Bridge in Los Angeles County,"Replace Bridge in Los Angeles County, part of the Highway Safety Improvement Program (HSIP). (Federal Project ID: Q101398)."

In [26]:
oct_2025 = "gs://calitp-analytics-data/data-analyses/dla/dla-iija/FMIS_Projects_Universe_IIJA_Reporting_10202025_agg.csv"

In [27]:
oct_df = pd.read_csv(oct_2025)

In [28]:
len(oct_df)

3194

In [29]:
oct_df.head(1)

,Unnamed: 0,Fmis Transaction Date,Project Number,Implementing Agency,Summary Recipient Defined Text Field 1 Value,Funding Type Code,Program Code,Program Code Description,Recipient Project Number,Improvement Type,Improvement Type Description,Old Project Title Desc,Obligations Amount,Total Cost Amount,Congressional District,District,County Code,County Name,County Name Abbrev,Implementing Agency Locode,Rtpa Name,Mpo Name,New Project Title,New Description Col
0,0,2022-01-20,31RA002,California,S AMBAG,IIJA-A,ER01,Emergency Supplement Funding,0518000118S,16|43,Right of Way|Utilities,MONTEREY COUNTY NEAR BIG SUR 2.3 MILES NORTH OF CASTRO CANYON BRIDGE TO 0.8 MILE SOUTH OF BIG SUR RIVER BRIDGE. EMERGENCY PROJECT - PERMANENT RESTORA,2983400,3370100,|20|,|05|,53,Monterey County,|MON|,NaN,NaN,NaN,Right of Way Project in Monterey County,"Right of Way Project in Monterey County, part of the Emergency Supplement Funding. (Federal Project ID: 31RA002)."

## Removing S***ba
### `data_utils`

In [30]:
def update_program_code_list2():
    updated_codes = to_snakecase(
        pd.read_excel(
            f"{GCS_FILE_PATH}/program_codes/FY21-22ProgramCodesAsOf5-25-2022.v2_expanded090823.xlsx"
        )
    )[["iija_program_code", "new_description"]]
    original_codes = to_snakecase(
        pd.read_excel(
            f"{GCS_FILE_PATH}/program_codes/Copy of lst_IIJA_Code_20230908.xlsx"
        )
    )[["iija_program_code", "description", "program_name"]]

    program_codes = pd.merge(
        updated_codes,
        original_codes,
        on="iija_program_code",
        how="outer",
        indicator=True,
    )
    program_codes["new_description"] = program_codes["new_description"].str.strip()

    program_codes.new_description.fillna(program_codes["description"], inplace=True)

    program_codes = program_codes.drop(columns={"description", "_merge"})

    def add_program_to_row(row):
        if "Program" not in row["program_name"]:
            return row["program_name"] + " Program"
        else:
            return row["program_name"]

    program_codes["program_name"] = program_codes.apply(add_program_to_row, axis=1)

    return program_codes

### `script_utils`

In [31]:
def county_district_crosswalk() -> pd.DataFrame:
    """
    Aggregate locodes dataset to find which
    districts a county lies in.
    """
    # Load locodes
    locodes_df = _script_utils.load_locodes()

    # Load counties
    county_base = _script_utils.load_county()

    county_district = locodes_df[["district", "county_name"]].drop_duplicates()

    county_info = pd.merge(
        county_base,
        county_district,
        how="left",
        left_on="county_description",
        right_on="county_name",
    ).drop(columns=["county_name"])
    return county_info

In [32]:
test1 = county_district_crosswalk()

In [33]:
test1.head()

  recipient_name county_description  county_code  district
0     California     Alameda County            1       4.0
1     California      Alpine County            3      10.0
2     California      Amador County            5      10.0
3     California       Butte County            7       3.0
4     California   Calaveras County            9      10.0