In [41]:
import pandas as pd
import geopandas as gpd
from shared_utils import geo_utils
from calitp_data_analysis.sql import get_engine
db_engine = get_engine()
import gcsfs
import google.auth
credentials, project = google.auth.default()
fs = gcsfs.GCSFileSystem()
import os

pd.set_option('display.max_columns', None)

In [42]:
GCS_FILE_PATH  = 'gs://calitp-analytics-data/data-analyses'

In [3]:
# Querying unique GTFS stops (lightweight)
with db_engine.connect() as connection:
    query = """
        SELECT
            name,
            stop_id,
            stop_key,
            stop_code,
            stop_name,
            location_type,
            ANY_VALUE(pt_geom) AS pt_geom
        FROM
            cal-itp-data-infra.mart_gtfs_rollup.fct_monthly_scheduled_stops
        WHERE(
        month_first_day BETWEEN DATE('2025-01-01') AND DATE('2025-12-01') 
        OR month_first_day BETWEEN DATE('2026-03-01') AND DATE('2026-06-01')
        )
        GROUP BY
            name,
            stop_id,
            stop_key,
            stop_code,
            stop_name,
            location_type
    """
    stops_unique = pd.read_sql(query, connection)

/home/jovyan/data-analyses/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:613: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

In [4]:
# # Querying unique GTFS stops (lightweight)
# with db_engine.connect() as connection:
#     query = """
#         SELECT
#             name,
#             stop_id,
#             stop_key,
#             stop_code,
#             stop_name,
#             location_type,
#             ANY_VALUE(pt_geom) AS pt_geom
#         FROM
#             cal-itp-data-infra.mart_gtfs_rollup.fct_monthly_scheduled_stops
#         WHERE
#             month_first_day BETWEEN DATE('2025-01-01') AND DATE('2025-12-01')
#         GROUP BY
#             name,
#             stop_id,
#             stop_key,
#             stop_code,
#             stop_name,
#             location_type
#     """
#     stops_unique = pd.read_sql(query, connection)

In [43]:
with db_engine.connect() as connection:
    query_bridge = """
        SELECT *
        FROM cal-itp-data-infra-staging.mart_transit_database.bridge_gtfs_analysis_name_x_ntd
    """
    bridge_gtfs = pd.read_sql(query_bridge, connection)

# save as parquet
bridge_gtfs.to_parquet("bridge_gtfs_analysis_name_x_ntd.parquet", engine="pyarrow", index=False)

/home/jovyan/data-analyses/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:613: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

In [62]:
rancho_rows = bridge_gtfs[
    bridge_gtfs["organization_name"].str.contains("Sacramento", case=False, na=False)
]

In [63]:
rancho_rows

,organization_name,organization_source_record_id,schedule_source_record_id,schedule_gtfs_dataset_name,analysis_name,regional_feed_type,county_name,caltrans_district,caltrans_district_name,caltrans_district_full,ntd_id,ntd_id_2022,rtpa_name,mpo_name
157,Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments

In [6]:
from shared_utils import geo_utils

In [7]:
stops_unique_gdf = (
    stops_unique
    .pipe(
        geo_utils.convert_to_gdf,
        geom_col="pt_geom",
        geom_type="point"
    )
)

In [8]:
print(type(stops_unique_gdf))
print(stops_unique_gdf.geometry.head())

<class 'geopandas.geodataframe.GeoDataFrame'>
0    POINT (-122.51895 37.92522)
1    POINT (-120.21773 39.19920)
2    POINT (-121.55045 39.48217)
3    POINT (-117.37635 33.19790)
4    POINT (-119.99161 38.92194)
Name: geometry, dtype: geometry

In [9]:
stops_unique_gdf = stops_unique_gdf.drop_duplicates(subset=["stop_id", "stop_name"])

In [10]:
stops_unique_gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 133560 entries, 0 to 1899936
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   name           133560 non-null  object
 1   stop_id        133560 non-null  object
 2   stop_key       133560 non-null  object
 3   stop_code      111856 non-null  object
 4   stop_name      133560 non-null  object
 5   location_type  77066 non-null   float64
 6   geometry       133560 non-null  geometry
dtypes: float64(1), geometry(1), object(5)
memory usage: 8.2+ MB

In [11]:
stops_unique_gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 133560 entries, 0 to 1899936
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   name           133560 non-null  object
 1   stop_id        133560 non-null  object
 2   stop_key       133560 non-null  object
 3   stop_code      111856 non-null  object
 4   stop_name      133560 non-null  object
 5   location_type  77066 non-null   float64
 6   geometry       133560 non-null  geometry
dtypes: float64(1), geometry(1), object(5)
memory usage: 8.2+ MB

In [12]:
stops_unique_gdf.name.nunique()

275

In [13]:
bridge_gtfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   organization_name              219 non-null    object
 1   organization_source_record_id  219 non-null    object
 2   schedule_source_record_id      219 non-null    object
 3   schedule_gtfs_dataset_name     219 non-null    object
 4   analysis_name                  219 non-null    object
 5   regional_feed_type             46 non-null     object
 6   county_name                    219 non-null    object
 7   caltrans_district              219 non-null    int64
 8   caltrans_district_name         219 non-null    object
 9   caltrans_district_full         219 non-null    object
 10  ntd_id                         174 non-null    object
 11  ntd_id_2022                    177 non-null    object
 12  rtpa_name                      212 non-null    object
 13  mpo_name                       174 non-null    object
dtypes: int64(1), object(13)
memory usage: 24.1+ KB

In [14]:
bridge_gtfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   organization_name              219 non-null    object
 1   organization_source_record_id  219 non-null    object
 2   schedule_source_record_id      219 non-null    object
 3   schedule_gtfs_dataset_name     219 non-null    object
 4   analysis_name                  219 non-null    object
 5   regional_feed_type             46 non-null     object
 6   county_name                    219 non-null    object
 7   caltrans_district              219 non-null    int64
 8   caltrans_district_name         219 non-null    object
 9   caltrans_district_full         219 non-null    object
 10  ntd_id                         174 non-null    object
 11  ntd_id_2022                    177 non-null    object
 12  rtpa_name                      212 non-null    object
 13  mpo_name                       174 non-null    object
dtypes: int64(1), object(13)
memory usage: 24.1+ KB

In [15]:
bridge_gtfs.head(5)

,organization_name,organization_source_record_id,schedule_source_record_id,schedule_gtfs_dataset_name,analysis_name,regional_feed_type,county_name,caltrans_district,caltrans_district_name,caltrans_district_full,ntd_id,ntd_id_2022,rtpa_name,mpo_name
0,Presidio Trust,recsBfXgev9ICDCY1,recIc6H6QCvQrBQxl,Bay Area 511 PresidiGo Schedule,Presidio Trust,Regional Subfeed,San Francisco,4,Bay Area / Oakland,04 - Bay Area / Oakland,None,None,Metropolitan Transportation Commission,Metropolitan Transportation Commission
1,San Joaquin Joint Powers Authority,recvUlrKS1N2mvAwk,rec7vVlnDHHfMjzoO,Gold Runner Schedule,San Joaquin Joint Powers Authority,None,San Joaquin,10,Stockton,10 - Stockton,None,None,San Joaquin Council of Governments,San Joaquin Council of Governments
2,City of Huntington Park,rec0mPaKPAdemkyOV,recyga5EW8Ly3EJTk,Huntington Park Schedule,City of Huntington Park,None,Los Angeles,7,Los Angeles / Ventura,07 - Los Angeles / Ventura,90267,90267,Southern California Association of Governments,Southern California Association of Governments
3,City of Laguna Beach,rec6Z3DnERm3OwFzw,recXPyi9Uiudn74nX,Laguna Beach Flex,City of Laguna Beach,None,Orange,12,Orange County,12 - Orange County,90119,90119,Southern California Association of Governments,Southern California Association of Governments
4,City of Turlock,recmQVsPDG6sLtD6j,rec8p8aIgJ66XnuqS,Turlock Schedule,City of Turlock,None,Stanislaus,10,Stockton,10 - Stockton,90201,90201,Stanislaus Council of Governments,Stanislaus Council of Governments

In [21]:
stops_with_crosswalk = stops_unique_gdf.merge(
    bridge_gtfs,
    left_on="name",       
    right_on="schedule_gtfs_dataset_name",  
    how="left"             
)

In [22]:
stops_with_crosswalk.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 133560 entries, 0 to 133559
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   name                           133560 non-null  object
 1   stop_id                        133560 non-null  object
 2   stop_key                       133560 non-null  object
 3   stop_code                      111856 non-null  object
 4   stop_name                      133560 non-null  object
 5   location_type                  77066 non-null   float64
 6   geometry                       133560 non-null  geometry
 7   organization_name              96362 non-null   object
 8   organization_source_record_id  96362 non-null   object
 9   schedule_source_record_id      96362 non-null   object
 10  schedule_gtfs_dataset_name     96362 non-null   object
 11  analysis_name                  96362 non-null   object
 12  regional_feed_type             14726 non-null   object
 13  county_name                    96362 non-null   object
 14  caltrans_district              96362 non-null   float64
 15  caltrans_district_name         96362 non-null   object
 16  caltrans_district_full         96362 non-null   object
 17  ntd_id                         85100 non-null   object
 18  ntd_id_2022                    85358 non-null   object
 19  rtpa_name                      94806 non-null   object
 20  mpo_name                       87517 non-null   object
dtypes: float64(2), geometry(1), object(18)
memory usage: 21.4+ MB

In [67]:
rancho_rows = stops_with_crosswalk[
    stops_with_crosswalk["analysis_name"].str.contains("Sacramento", case=False, na=False)
]

rancho_rows

,name,stop_id,stop_key,stop_code,stop_name,location_type,geometry,organization_name,organization_source_record_id,schedule_source_record_id,schedule_gtfs_dataset_name,analysis_name,regional_feed_type,county_name,caltrans_district,caltrans_district_name,caltrans_district_full,ntd_id,ntd_id_2022,rtpa_name,mpo_name
7913,South County Transit Link Schedule,10014,325ae58eadfbd24ec9b5416fea2af6a0,10014,Q St & 16th (EB),NaN,POINT (-121.48881 38.57036),Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments
11881,South County Transit Link Schedule,10008,f5e48d1ba10c3c28454648a5201a02bd,10008,30th St & R St (NB),NaN,POINT (-121.47034 38.56409),Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments
11955,South County Transit Link Schedule,10018,b686577269982631331fac783f19239b,10018,North South St & Warehouse St (NB),NaN,POINT (-121.51314 38.24084),Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments
18152,South County Transit Link Schedule,10005,fef2d17ced5edadfc669837edf03b64a,10005,Wyhdham Dr & Lindbrock Way (WB),NaN,POINT (-121.42303 38.46869),Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments
22059,South County Transit Link Schedule,10001,73d2efa73f8963ab7248b7f3a32a1918,10001,Sacramento St & West Oak St (NB),NaN,POINT (-121.27221 38.13312),Sacramento County,recsrpnpj2oZXBvE6,recKYQPnCKuxQQ1B9,South County Transit Link Schedule,Sacramento County,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,9R02-90216,90216,Sacramento Area Council of Governments,Sacramento Area Council of Governments
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131212,Sacramento Schedule,1134,58ed18c4f46a5f78f52c5a07d13641f5,1134,12TH ST & E ST (SB),NaN,POINT (-121.48867 38.58487),City of Rancho Cordova,rec43oyrfhtPDdRHj,recbzZQUIdMmFvm1r,Sacramento Schedule,Sacramento Regional Transit District,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,None,None,Sacramento Area Council of Governments,Sacramento Area Council of Governments
131213,Sacramento Schedule,1722,461e99f1af7461d0ce312252f5fd6ed1,1722,J ST & 27TH ST (EB),NaN,POINT (-121.47029 38.57405),City of Rancho Cordova,rec43oyrfhtPDdRHj,recbzZQUIdMmFvm1r,Sacramento Schedule,Sacramento Regional Transit District,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,None,None,Sacramento Area Council of Governments,Sacramento Area Council of Governments
133545,Sacramento Schedule,1066,f4db9d8526497efca8163849a4901b54,1066,H ST & 14TH ST (EB),NaN,POINT (-121.48654 38.58090),City of Rancho Cordova,rec43oyrfhtPDdRHj,recbzZQUIdMmFvm1r,Sacramento Schedule,Sacramento Regional Transit District,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,None,None,Sacramento Area Council of Governments,Sacramento Area Council of Governments
133546,Sacramento Schedule,11217,11e7f7604d1924c4765931a213224e63,11217,EAST BIDWELL & ORCHARD DR (WB),NaN,POINT (-121.15804 38.67095),City of Rancho Cordova,rec43oyrfhtPDdRHj,recbzZQUIdMmFvm1r,Sacramento Schedule,Sacramento Regional Transit District,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,None,None,Sacramento Area Council of Governments,Sacramento Area Council of Governments
133547,Sacramento Schedule,1135,d6ed31c8793280c438053ce2eacdf86a,1135,12TH ST & H ST (SB),NaN,POINT (-121.48978 38.58227),City of Rancho Cordova,rec43oyrfhtPDdRHj,recbzZQUIdMmFvm1r,Sacramento Schedule,Sacramento Regional Transit District,None,Sacramento,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,None,None,Sacramento Area Council of Governments,Sacramento Area Council of Governments

In [23]:
# List of variant rows to drop (no org info, but other variants in group have org info)
drop_names = [
    'Anaheim Resort Schedule v2', 'Tri-Valley Wheels Schedule', 'Lynwood Schedule',
    'Mountain Transit GMV Schedule', 'Nevada County Remix Schedule',
    'Roseville Transit GMV Schedule', 'Roseville Transit TripShot Schedule',
    'TCRTA Schedule Historic 2', 'Tahoe Transportation District GMV Schedule',
    'Victor Valley GMV Schedule', 'eTrans Schedule Remix',
    'eTrans Schedule Trillium', 'Bellflower Remix Schedule',
    'Capitol Corridor Schedule', 'Commute.org Schedules',
    'El Monte RTAP Schedule', 'Vacaville Schedule', 'Marin GMV Schedule',
    'Petaluma GMV Schedule', 'Union City GMV Schedule',
    'South San Francisco Schedule', 'Basin Transit GMV Schedule',
    'Vine GMV Schedule', 'Caltrain Schedule',
    'Big Blue Bus Swiftly Schedule', 'Emery Go-Round TripShot Schedule',
    'Santa Rosa CityBus GMV Schedule', 'Merced GMV Schedule',
    'SolTrans Schedule', 'eTrans Schedule', 'WestCAT Schedule', 'MVGO Schedule',
    'Cerritos on Wheels Schedule', 'San Francisco Bay Ferry Schedule',
    'SMART Schedule', 'Lawndale Beat GMV Schedule',
    'Mountain View Community Shuttle Schedule', 'Desert Roadrunner GMV Schedule',
    'ACE Schedule', 'AC Transit Schedule', 'SCVTA Schedule', 'SamTrans Schedule',
    'Amtrak San Joaquins Schedule', 'Fairfield Schedule', 'Rio Vista Schedule',
    'County Connection Schedule', 'TCRTA TripShot Schedule'
]
# Drop these rows
stops_with_crosswalk_cleaned = stops_with_crosswalk[~stops_with_crosswalk['name'].isin(drop_names)].reset_index(drop=True)

In [24]:
def export_gdf(gdf, filename: str):
    # Save GeoParquet locally
    gdf.to_parquet(f"{filename}.parquet", engine="pyarrow", index=False)

    # Full GCS path including folder
    gcs_path = f"{GCS_FILE_PATH}/transit_provider_dashboard/{filename}.parquet"

    # Upload to GCS
    fs.put(
        f"{filename}.parquet",
        gcs_path,
        token=credentials.token
    )

    # Remove local file
    os.remove(f"{filename}.parquet")
    print(f"saved {gcs_path}")

In [25]:
# Store data in warehouse
export_gdf(stops_with_crosswalk_cleaned, "stop_data_cleaned")

saved gs://calitp-analytics-data/data-analyses/transit_provider_dashboard/stop_data_cleaned.parquet