In [1]:
import sys
!{sys.executable} -m ensurepip --upgrade

Looking in links: /tmp/tmphvwyc4u0
Requirement already satisfied: setuptools in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (82.0.1)
Requirement already satisfied: pip in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (24.0)

In [2]:
import sys
!{sys.executable} -m pip install rapidfuzz

Requirement already satisfied: rapidfuzz in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (3.14.5)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip

In [3]:
import gcsfs

fs = gcsfs.GCSFileSystem()

In [4]:
# Importing necessary package 
import pandas as pd 
import geopandas as gpd
import google.auth
import os
import gcsfs
import requests
import fsspec
from rapidfuzz import process, fuzz
import re
from calitp_data_analysis.sql import get_engine
db_engine = get_engine()
credentials, project = google.auth.default()
fs = gcsfs.GCSFileSystem()
from segment_speed_utils.project_vars import PUBLIC_GCS
from pandas import ExcelWriter

pd.set_option('display.max_columns', None)

In [5]:
GCS_FILE_PATH  = 'gs://calitp-analytics-data/data-analyses'

In [6]:
# Load the stored ACS dataset from the specified GCS file path.
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/census_tracts_data_2024.parquet", "rb") as f:
    tracts_ca_acs = gpd.read_parquet(f)

In [7]:
# Load the stored organization dataset from the specified GCS file path.
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/organization_data_2025_10_16.parquet", "rb") as f:
    valid_organization_full = pd.read_parquet(f)

In [8]:
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/ridership_data_2024.parquet", "rb") as f:
    ridership_data_grouped = pd.read_parquet(f)

In [9]:
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/stop_data_cleaned.parquet", "rb") as f:
    orgs_stops_clean = gpd.read_parquet(f)

In [10]:
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/census_ca_data_2024.parquet", "rb") as f:
    ca_totals_acs = gpd.read_parquet(f)

In [11]:
valid_organization_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   key                         199 non-null    object
 1   name                        199 non-null    object
 2   source_record_id            199 non-null    object
 3   organization_type           199 non-null    object
 4   ntd_id                      165 non-null    object
 5   ntd_id_2022                 167 non-null    object
 6   ntd_agency_info_key         147 non-null    object
 7   public_currently_operating  199 non-null    bool
 8   _is_current                 199 non-null    bool
 9   _valid_from                 199 non-null    datetime64[ns, UTC]
 10  _valid_to                   199 non-null    datetime64[ns, UTC]
 11  _valid_from_local           199 non-null    datetime64[ns]
 12  _valid_to_local             199 non-null    datetime64[ns]
dtypes: bool(2), datetime64[ns, UTC](2), datetime64[ns](2), object(7)
memory usage: 17.6+ KB

## Spatial Analysis: Stop Buffers and Census Tract Intersections

In [12]:
sac_unique_rows = (
    orgs_stops_clean[
        orgs_stops_clean['rtpa_name'].str.contains('sac', case=False, na=False)
    ]
    .drop_duplicates(subset=['rtpa_name'])
)

sac_unique_rows

,name,stop_id,stop_key,stop_code,stop_name,location_type,geometry,organization_name,organization_source_record_id,schedule_source_record_id,schedule_gtfs_dataset_name,analysis_name,regional_feed_type,county_name,caltrans_district,caltrans_district_name,caltrans_district_full,ntd_id,ntd_id_2022,rtpa_name,mpo_name
102,Yolobus Schedule,23473,a9504b873a5cbccc1be46452cd7c4d48,23473,West Sacramento Transit Center,0.0,POINT (-121.52248 38.58093),Yolo County Transportation District,recH2FdHvrL7nIpHA,recEsm4bknyyk4UAS,Yolobus Schedule,Yolo County Transportation District,None,Yolo,3.0,Marysville / Sacramento,03 - Marysville / Sacramento,90090,90090,Sacramento Area Council of Governments,Sacramento Area Council of Governments

In [13]:
columns_to_keep = [
    "name", "ntd_id", "ntd_id_2022", "stop_id", "stop_name", 
    "schedule_gtfs_dataset_name", "organization_source_record_id", 
    "geometry", "analysis_name", "organization_name"
]

stops_clean_subset = orgs_stops_clean[columns_to_keep].copy()

In [14]:
# Clean names to remove noise words
remove_words = ['Schedule', 'GMV', 'TripShot', 'Remix', 'v2', 'Historic', 'Cal-ITP', 'RTAP']

def clean_name(name):
    for w in remove_words:
        name = re.sub(rf'\b{w}\b', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

In [15]:
# Add cleaned columns
stops_clean_subset['name_clean'] = stops_clean_subset['name'].apply(clean_name)
valid_organization_full['name_clean'] = valid_organization_full['name'].apply(clean_name)

In [16]:
base = stops_clean_subset.copy()
valid_names_clean = valid_organization_full["name_clean"].tolist()



def fuzzy_match_org(name, valid_names, threshold=90):
    match = process.extractOne(name, valid_names, scorer=fuzz.WRatio)

    if match and match[1] >= threshold:
        matched_name_clean = match[0]

        idx = valid_organization_full.index[
            valid_organization_full["name_clean"] == matched_name_clean
        ][0]

        return (
            valid_organization_full.loc[idx, "source_record_id"],
            valid_organization_full.loc[idx, "name"]
        )

    return None, None



target_names = [
    "Auburn Schedule",
    "Fairfield Schedule",
    "Gold Coast Schedule",
    "Golden Gate Bridge Schedule",
    "Moorpark Schedule",
    "Morro Bay Cal-ITP Schedule",
    "Simi Valley Schedule",
    "South San Francisco Schedule",
    "Trinity Schedule",
    "Thousand Oaks Schedule"
]

mask = (
    base["organization_source_record_id"].isna()
    & base["name"].isin(target_names)
)

In [17]:
subset = base.loc[mask].copy()

matches = subset["name_clean"].apply(
    lambda x: fuzzy_match_org(x, valid_names_clean)
)

subset["organization_source_record_id"] = [m[0] for m in matches]
subset["analysis_name"] = [m[1] for m in matches]

In [18]:
base.loc[mask, "organization_source_record_id"] = subset["organization_source_record_id"]
base.loc[mask, "analysis_name"] = subset["analysis_name"]

In [19]:
orgs_stops_merged = base.merge(
    valid_organization_full[
        ["source_record_id", "key", "organization_type", "ntd_id", "ntd_id_2022"]
    ],
    left_on="organization_source_record_id",
    right_on="source_record_id",
    how="left"
)

In [20]:
filled_rows = subset[subset["organization_source_record_id"].notna()]

filled_unique = (
    filled_rows[
        ["name", "organization_name", "organization_source_record_id", "analysis_name"]
    ]
    .drop_duplicates()
    .sort_values("name")
)

print(f"Filled rows: {filled_unique['name'].nunique()}")
filled_unique

Filled rows: 10

,name,organization_name,organization_source_record_id,analysis_name
9237,Auburn Schedule,None,recbW86Xrtuw8PhiU,City of Auburn
118,Fairfield Schedule,None,recot6qBamlOoLcrM,City of Fairfield
23,Gold Coast Schedule,None,recS7GnKTcQVX20HE,Gold Coast Transit District
80,Golden Gate Bridge Schedule,None,recoX7qMhlPrgfuz3,"Golden Gate Bridge, Highway and Transportation..."
1077,Moorpark Schedule,None,recojKzQsBzE1hjVu,City of Moorpark
18648,Morro Bay Cal-ITP Schedule,None,recH53ghrYpk4gKhe,City of Morro Bay
165,Simi Valley Schedule,None,rec1ErIn9gG1Isk5W,City of Simi Valley
2181,South San Francisco Schedule,None,recPtsCi89lKcXaTW,City of South San Francisco
69,Thousand Oaks Schedule,None,recPJULRJk1Yn824N,City of Thousand Oaks
1162,Trinity Schedule,None,recK5xIowqx4sGVMT,Trinity County

In [21]:
orgs_stops_merged.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 133556 entries, 0 to 133555
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   name                           133556 non-null  object
 1   ntd_id_x                       85055 non-null   object
 2   ntd_id_2022_x                  85312 non-null   object
 3   stop_id                        133556 non-null  object
 4   stop_name                      133556 non-null  object
 5   schedule_gtfs_dataset_name     96325 non-null   object
 6   organization_source_record_id  97688 non-null   object
 7   geometry                       133556 non-null  geometry
 8   analysis_name                  97688 non-null   object
 9   organization_name              96325 non-null   object
 10  name_clean                     133556 non-null  object
 11  source_record_id               87122 non-null   object
 12  key                            87122 non-null   object
 13  organization_type              87122 non-null   object
 14  ntd_id_y                       82543 non-null   object
 15  ntd_id_2022_y                  82647 non-null   object
dtypes: geometry(1), object(15)
memory usage: 16.3+ MB

In [22]:
orgs_stops_merged.head(5)

,name,ntd_id_x,ntd_id_2022_x,stop_id,stop_name,schedule_gtfs_dataset_name,organization_source_record_id,geometry,analysis_name,organization_name,name_clean,source_record_id,key,organization_type,ntd_id_y,ntd_id_2022_y
0,Marin GMV Schedule,None,None,498081,Sir Francis Drake Blvd & Bolinas Rd,None,None,POINT (-122.56049 37.96974),None,None,Marin,NaN,NaN,NaN,NaN,NaN
1,Tri-Valley Wheels Schedule,None,None,2-023,BLUEBELL DR & NORTH LIVERMORE PARK,None,None,POINT (-121.74443 37.71878),None,None,Tri-Valley Wheels,NaN,NaN,NaN,NaN,NaN
2,Tri-Valley Wheels Schedule,None,None,8-019,SANTA RITA RD & MOHR AVE EB,None,None,POINT (-121.87570 37.68123),None,None,Tri-Valley Wheels,NaN,NaN,NaN,NaN,NaN
3,"TART, North Lake Tahoe Schedule",None,None,3045,Deerfield Dr at Crossroads Center (Post Office),"TART, North Lake Tahoe Schedule",reckjhbXRQIr4k50W,POINT (-120.20909 39.32044),"Tahoe Truckee Area Regional Transportation, No...",North Lake Tahoe Express,"TART, North Lake Tahoe",NaN,NaN,NaN,NaN,NaN
4,B-Line Schedule,90208,90208,370,E 20th St & Chico Mall,B-Line Schedule,recf7l9tozKXOmqqZ,POINT (-121.80414 39.72721),Butte County Association of Governments,Butte County Association of Governments,B-Line,recf7l9tozKXOmqqZ,8ba736645cf9016bd129181068a9bc7b,MPO/RTPA,90208,90208

In [23]:
# Find rows where organization_source_record_id is still missing
still_missing = orgs_stops_merged[orgs_stops_merged['organization_source_record_id'].isna()]

# Get unique names
unique_missing_names = still_missing['name'].unique()

print(f"Total unique names still missing: {len(unique_missing_names)}")
print(unique_missing_names)

Total unique names still missing: 66
['Marin GMV Schedule' 'Tri-Valley Wheels Schedule'
 'Anaheim Resort Schedule v2' 'Big Blue Bus Swiftly Schedule'
 'WestCAT Schedule' 'Marin Optibus Schedule' 'Rosemead Passio Schedule'
 'Roseville Transit GMV Schedule' 'Amtrak San Joaquins Schedule'
 'SolTrans Schedule' 'Vacaville Schedule' 'Vine Schedule'
 'Mountain Transit GMV Schedule'
 'Tahoe Transportation District GMV Schedule' 'County Connection Schedule'
 'Santa Rosa CityBus GMV Schedule' 'Vine GMV Schedule' 'MVGO Schedule'
 'Nevada County Schedule' 'Mountain View Community Shuttle Schedule'
 'SMART Schedule' 'Sonoma County Transit Schedule' 'Commute.org Schedules'
 'Anaheim Resort Schedule' 'TCRTA TripShot Schedule'
 'Clovis PassioGo Schedule' 'Trinity Remix Schedule'
 'Emery Go-Round TripShot Schedule' 'BART Schedule'
 'Desert Roadrunner GMV Schedule' 'Basin Transit GMV Schedule'
 'Caltrain Schedule' 'Merced GMV Schedule' 'Union City GMV Schedule'
 'Yuba-Sutter PassioGo Schedule' 'Dana Point Trolley PassioGo Schedule'
 'Cerritos on Wheels Website Schedule' 'VCTC Schedule' 'eTrans Schedule'
 'Dana Point Trolley Schedule' 'Peppedine University Shuttles Schedule'
 'TCRTA Schedule Historic 2' 'Rio Vista Schedule'
 'Bellflower Bus Schedule' 'Cerritos on Wheels Schedule'
 'Beaumont Pass Schedule' 'Capitol Corridor Schedule'
 'San Francisco Bay Ferry Schedule' 'LAX Shuttles Schedule'
 'CSULB Shuttle PassioGo Schedule' 'Fric and Frac Schedule'
 'Laguna Niguel Schedule' 'LAX FlyAway Schedule'
 'eTrans Schedule Trillium'
 'University of San Diego Tram Services Schedule' 'ACE Schedule'
 'Bulldog Express PassioGo Schedule' 'Ridgecrest Schedule'
 'AC Transit Schedule' 'Bay Area 511 Regional Schedule' 'SCVTA Schedule'
 'SamTrans Schedule' 'Sonoma Schedule' 'Victor Valley GMV Schedule'
 'Guadalupe Flyer Schedule' 'Bay Area 511 Emery Express Schedule']

In [24]:
# Manual mapping for remaining unmatched
manual_matches = {
    # "BART Schedule": "San Francisco Bay Area Rapid Transit District",
    # "Vine Schedule": "Napa Valley Transportation Authority",
    # "VCTC Schedule": "Ventura County Transportation Commission",
    "Sonoma County Transit Schedule": "Sonoma County"
    
}

# Loop over manual matches and update orgs_stops_merged
for gtfs_name, org_name in manual_matches.items():
    # Get valid_organization_full row
    org_row = valid_organization_full[valid_organization_full['name'] == org_name]
    
    if not org_row.empty:
        source_id = org_row['source_record_id'].values[0]
        key = org_row['key'].values[0]
        org_type = org_row['organization_type'].values[0]
        
        # Update orgs_stops_merged where the GTFS name matches
        mask = orgs_stops_merged['name'] == gtfs_name
        orgs_stops_merged.loc[mask, 'organization_source_record_id'] = source_id
        orgs_stops_merged.loc[mask, 'analysis_name'] = org_name
        orgs_stops_merged.loc[mask, 'key'] = key
        orgs_stops_merged.loc[mask, 'organization_type'] = org_type

In [25]:
orgs_stops_merged.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 133556 entries, 0 to 133555
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   name                           133556 non-null  object
 1   ntd_id_x                       85055 non-null   object
 2   ntd_id_2022_x                  85312 non-null   object
 3   stop_id                        133556 non-null  object
 4   stop_name                      133556 non-null  object
 5   schedule_gtfs_dataset_name     96325 non-null   object
 6   organization_source_record_id  98702 non-null   object
 7   geometry                       133556 non-null  geometry
 8   analysis_name                  98702 non-null   object
 9   organization_name              96325 non-null   object
 10  name_clean                     133556 non-null  object
 11  source_record_id               87122 non-null   object
 12  key                            88136 non-null   object
 13  organization_type              88136 non-null   object
 14  ntd_id_y                       82543 non-null   object
 15  ntd_id_2022_y                  82647 non-null   object
dtypes: geometry(1), object(15)
memory usage: 16.3+ MB

In [26]:
orgs_stops_merged.name.nunique()

275

In [27]:
# combined_names_dict = {
#     "Sacramento Regional Transit District": "Sacramento Schedule",
#     "City of Rancho Cordova": "Sacramento Schedule",
#     "Flagship Cruises and Events Inc.": "San Diego Schedule",
#     "San Diego International Airport": "San Diego Schedule",
#     "City of Arcata": "Humboldt Schedule",
#     "City of Eureka": "Humboldt Schedule",
#     "San Francisco Bay Area Water Emergency Transit Authority": "San Francisco Bay Ferry and Oakland Alameda Water Shuttle Schedule",
#     "City of Alameda": "San Francisco Bay Ferry and Oakland Alameda Water Shuttle Schedule",
# }

In [28]:
# orgs_stops_merged['name'] = (
#     orgs_stops_merged['organization_name']
#     .map(combined_names_dict)
#     .fillna(orgs_stops_merged['name'])
# )

In [29]:
orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Anaheim Resort Schedule",
    "analysis_name"
] = "Anaheim Transportation Network"


orgs_stops_merged.loc[
    orgs_stops_merged["name"].isin(["SLO Schedule", "SLO Peak Transit Schedule"]),
    "analysis_name"
] = "City of San Luis Obispo"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Bay Area 511 Dumbarton Express Schedule",
    "analysis_name"
] = "Dumbarton Bridge Regional Operations Consortium"


orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Bay Area 511 Sonoma County Transit Schedule",
    "analysis_name"
] = "Cloverdale Transit"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "South County Transit Link Schedule",
    "analysis_name"
] = "South County Transit Link"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Bay Area 511 Golden Gate Transit Schedule",
    "analysis_name"
] = "Golden Gate Transit"


orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Golden Gate Bridge Schedule",
    "analysis_name"
] = "Golden Gate Bridge"


orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Bay Area 511 Golden Gate Ferry Schedule",
    "analysis_name"
] = "Golden Gate Ferry"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "LA Metro Bus Schedule",
    "organization_name"
] = "LA Metro Bus"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "LA Metro Rail Schedule",
    "organization_name"
] = "LA Metro Rail"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Golden Gate Park Shuttle Schedule",
    "analysis_name"
] = "SF Golden Gate Park Shuttle"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "Bay Area 511 Muni Schedule",
    "analysis_name"
] = "SF Muni"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "SLO Peak Transit Schedule",
    "analysis_name"
] = "SLO Peak Transit"

orgs_stops_merged.loc[
    orgs_stops_merged["name"] == "SLO Schedule",
    "analysis_name"
] = "City of San Luis Obispo"

In [30]:
# Reproject to match census tracts CRS
orgs_stops_merged = orgs_stops_merged.to_crs(tracts_ca_acs.crs)

In [31]:
orgs_stop_buffered = orgs_stops_merged.copy()
orgs_stop_buffered["geometry"] = orgs_stop_buffered.geometry.buffer(804.672)

In [33]:
orgs_stop_dissolved = orgs_stop_buffered.dissolve(by='name')

In [34]:
orgs_stop_buffered.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 133439 entries, 0 to 133555
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   name                           133439 non-null  object
 1   ntd_id_x                       84938 non-null   object
 2   ntd_id_2022_x                  85195 non-null   object
 3   stop_id                        133439 non-null  object
 4   stop_name                      133439 non-null  object
 5   schedule_gtfs_dataset_name     96208 non-null   object
 6   organization_source_record_id  98585 non-null   object
 7   geometry                       133439 non-null  geometry
 8   analysis_name                  98666 non-null   object
 9   organization_name              96208 non-null   object
 10  name_clean                     133439 non-null  object
 11  source_record_id               87005 non-null   object
 12  key                            88019 non-null   object
 13  organization_type              88019 non-null   object
 14  ntd_id_y                       82426 non-null   object
 15  ntd_id_2022_y                  82530 non-null   object
dtypes: geometry(1), object(15)
memory usage: 17.3+ MB

In [35]:
orgs_stop_dissolved = orgs_stop_dissolved.reset_index()

In [36]:
orgs_stop_dissolved.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           279 non-null    object
 1   geometry                       279 non-null    geometry
 2   ntd_id_x                       160 non-null    object
 3   ntd_id_2022_x                  163 non-null    object
 4   stop_id                        279 non-null    object
 5   stop_name                      279 non-null    object
 6   schedule_gtfs_dataset_name     203 non-null    object
 7   organization_source_record_id  214 non-null    object
 8   analysis_name                  215 non-null    object
 9   organization_name              203 non-null    object
 10  name_clean                     279 non-null    object
 11  source_record_id               174 non-null    object
 12  key                            175 non-null    object
 13  organization_type              175 non-null    object
 14  ntd_id_y                       149 non-null    object
 15  ntd_id_2022_y                  151 non-null    object
dtypes: geometry(1), object(15)
memory usage: 35.0+ KB

In [37]:
orgs_stop_dissolved.head(5)

,name,geometry,ntd_id_x,ntd_id_2022_x,stop_id,stop_name,schedule_gtfs_dataset_name,organization_source_record_id,analysis_name,organization_name,name_clean,source_record_id,key,organization_type,ntd_id_y,ntd_id_2022_y
0,AC Transit Schedule,"MULTIPOLYGON (((-212684.433 -24900.213, -21276...",None,None,4489,Broadway Av & Rivers St,None,None,None,None,AC Transit,None,None,None,None,None
1,ACE Schedule,"MULTIPOLYGON (((-167527.197 -74692.199, -16754...",None,None,TRC,Tracy Station,None,None,None,None,ACE,None,None,None,None,None
2,Alhambra Schedule,"POLYGON ((169677.509 -438033.424, 169624.478 -...",90247,90247,2619846,Valley & Edgewood,Alhambra Schedule,recNaKvzVQhGX1puu,City of Alhambra,City of Alhambra,Alhambra,recNaKvzVQhGX1puu,897ce086b03388bc914f5c239298fb85,City/Town,90247,90247
3,Amador Schedule,"MULTIPOLYGON (((-79576.548 30778.572, -79623.5...",9R02-91000,91000,19027,Buckhorn Ridge Loop (Pioneer Park),Amador Schedule,recSBFiK95hJnJuYx,Amador Regional Transit System,Amador Regional Transit System,Amador,recSBFiK95hJnJuYx,71b58e792726688aef31d4712480d350,Independent Agency,9R02-91000,91000
4,Amtrak San Joaquins Schedule,"MULTIPOLYGON (((-179364.815 -114804.005, -1794...",None,None,bSPX,Sparks Bus Stop,None,None,None,None,Amtrak San Joaquins,None,None,None,None,None

In [38]:
# Compute the intersection between buffered stops and census tracts.
geometry_intersect = gpd.overlay(
    orgs_stop_dissolved, 
    tracts_ca_acs, 
    how = 'intersection', 
    keep_geom_type=True)

In [39]:
# Calculate the area of each intersected geometry in square meters.
geometry_intersect['area_2'] = geometry_intersect.geometry.area

In [40]:
geometry_intersect.head(2)

,name,ntd_id_x,ntd_id_2022_x,stop_id,stop_name,schedule_gtfs_dataset_name,organization_source_record_id,analysis_name,organization_name,name_clean,source_record_id,key,organization_type,ntd_id_y,ntd_id_2022_y,STATEFP,COUNTYFP,TRACTCE,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,NAMELSADCO,STATE_NAME,LSAD,ALAND,AWATER,total_pop,poverty_pop,non_us_citizen,male_65_to_66,male_67_to_69,male_70_to_74,male_75_to_79,male_80_to_84,male_85_and_over,female_65_to_66,female_67_to_69,female_70_to_74,female_75_to_79,female_80_to_84,female_85_and_over,male_15_17,male_18_19,male_20,male_21,male_22_24,female_15_17,female_18_19,female_20,female_21,female_22_24,median_household_income,income_less_10000,income_10000_14999,income_15000_24999,income_25000_34999,income_35000_49999,income_50000_64999,income_65000_74999,workers_with_no_car,households_with_no_cars,public_asst_pop,veteran_pop,county_name,inc_extremelylow,inc_verylow,inc_low,male_seniors,female_seniors,male_youth,female_youth,disabled_pop,area_m2,geometry,area_2
0,AC Transit Schedule,None,None,4489,Broadway Av & Rivers St,None,None,None,None,AC Transit,None,None,None,None,None,06,001,423000,1400000US06001423000,06001423000,4230,Census Tract 4230,CA,Alameda County,California,CT,730083,0,4478,637,533,13,16,160,91,29,69,69,60,113,28,36,56,38,134,7,121,145,78,36,0,105,93,110536,474,171,227,226,486,344,208,199,261,241,79,Alameda,872,712,552,378,362,445,312,447,730068.706503,"POLYGON ((-199666.745 -13709.245, -199647.316 ...",730068.706503
1,AC Transit Schedule,None,None,4489,Broadway Av & Rivers St,None,None,None,None,AC Transit,None,None,None,None,None,06,001,422200,1400000US06001422200,06001422200,4222,Census Tract 4222,CA,Alameda County,California,CT,675011,0,3313,188,217,10,29,35,17,9,57,0,63,74,65,32,22,3,10,67,0,9,31,16,32,0,34,99379,193,128,159,82,227,197,113,62,173,57,51,Alameda,480,309,310,157,256,89,113,320,674019.805718,"POLYGON ((-200507.136 -13116.597, -200491.926 ...",674019.805718

In [41]:
geometry_intersect.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 25508 entries, 0 to 25507
Data columns (total 77 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           25508 non-null  object
 1   ntd_id_x                       15557 non-null  object
 2   ntd_id_2022_x                  15661 non-null  object
 3   stop_id                        25508 non-null  object
 4   stop_name                      25508 non-null  object
 5   schedule_gtfs_dataset_name     18826 non-null  object
 6   organization_source_record_id  19351 non-null  object
 7   analysis_name                  19387 non-null  object
 8   organization_name              18826 non-null  object
 9   name_clean                     25508 non-null  object
 10  source_record_id               16985 non-null  object
 11  key                            17098 non-null  object
 12  organization_type              17098 non-null  object
 13  ntd_id_y                       15189 non-null  object
 14  ntd_id_2022_y                  15256 non-null  object
 15  STATEFP                        25508 non-null  object
 16  COUNTYFP                       25508 non-null  object
 17  TRACTCE                        25508 non-null  object
 18  GEOIDFQ                        25508 non-null  object
 19  GEOID                          25508 non-null  object
 20  NAME                           25508 non-null  object
 21  NAMELSAD                       25508 non-null  object
 22  STUSPS                         25508 non-null  object
 23  NAMELSADCO                     25508 non-null  object
 24  STATE_NAME                     25508 non-null  object
 25  LSAD                           25508 non-null  object
 26  ALAND                          25508 non-null  int64
 27  AWATER                         25508 non-null  int64
 28  total_pop                      25508 non-null  int64
 29  poverty_pop                    25508 non-null  int64
 30  non_us_citizen                 25508 non-null  int64
 31  male_65_to_66                  25508 non-null  int64
 32  male_67_to_69                  25508 non-null  int64
 33  male_70_to_74                  25508 non-null  int64
 34  male_75_to_79                  25508 non-null  int64
 35  male_80_to_84                  25508 non-null  int64
 36  male_85_and_over               25508 non-null  int64
 37  female_65_to_66                25508 non-null  int64
 38  female_67_to_69                25508 non-null  int64
 39  female_70_to_74                25508 non-null  int64
 40  female_75_to_79                25508 non-null  int64
 41  female_80_to_84                25508 non-null  int64
 42  female_85_and_over             25508 non-null  int64
 43  male_15_17                     25508 non-null  int64
 44  male_18_19                     25508 non-null  int64
 45  male_20                        25508 non-null  int64
 46  male_21                        25508 non-null  int64
 47  male_22_24                     25508 non-null  int64
 48  female_15_17                   25508 non-null  int64
 49  female_18_19                   25508 non-null  int64
 50  female_20                      25508 non-null  int64
 51  female_21                      25508 non-null  int64
 52  female_22_24                   25508 non-null  int64
 53  median_household_income        25508 non-null  int64
 54  income_less_10000              25508 non-null  int64
 55  income_10000_14999             25508 non-null  int64
 56  income_15000_24999             25508 non-null  int64
 57  income_25000_34999             25508 non-null  int64
 58  income_35000_49999             25508 non-null  int64
 59  income_50000_64999             25508 non-null  int64
 60  income_65000_74999             25508 non-null  int64
 61  workers_with_no_car            25508 non-null  int64
 62  households_with_no_cars        25508 non-null  int64
 63  public_asst_pop                25508 non-null  int64
 64  veteran_pop                    25508 non-null  int64
 65  county_name                    25508 non-null  object
 66  inc_extremelylow               25508 non-null  int64
 67  inc_verylow                    25508 non-null  int64
 68  inc_low                        25508 non-null  int64
 69  male_seniors                   25508 non-null  int64
 70  female_seniors                 25508 non-null  int64
 71  male_youth                     25508 non-null  int64
 72  female_youth                   25508 non-null  int64
 73  disabled_pop                   25508 non-null  int64
 74  area_m2                        25508 non-null  float64
 75  geometry                       25508 non-null  geometry
 76  area_2                         25508 non-null  float64
dtypes: float64(2), geometry(1), int64(47), object(27)
memory usage: 15.0+ MB

## Adjusting Population and Demographic Metrics for Stop Service Areas

In [42]:
# Adjust total population by the proportion of the tract area that intersects the stop buffer.
# Calculate the proportion of each tract's area that intersects the stop buffer
geometry_intersect['area_ratio'] = geometry_intersect['area_2'] / geometry_intersect['area_m2']

In [43]:
# Define demographic and socioeconomic columns to be adjusted by area ratio
cols_to_weight = [
    'total_pop', 'poverty_pop', 'non_us_citizen', 'workers_with_no_car', 
    'households_with_no_cars', 'disabled_pop', 'public_asst_pop', 
    'inc_extremelylow', 'inc_verylow', 'inc_low', 
    'male_seniors', 'female_seniors', 'veteran_pop', 'male_youth',  'female_youth'
]

# Apply area ratio to create adjusted metrics
geometry_intersect[[f'{col}_adj' for col in cols_to_weight]] = (
    geometry_intersect[cols_to_weight].multiply(geometry_intersect['area_ratio'], axis=0)
)

In [44]:
# Stop level demography data 
filtered_final_data = geometry_intersect[['name', 'organization_type', 'organization_name',  'analysis_name', 'ntd_id_y', 'ntd_id_2022_y', 'stop_id', 'stop_name', 
                                         'GEOIDFQ', 'geometry', 'area_2',	'total_pop_adj',	'poverty_pop_adj',	
                                          'non_us_citizen_adj',	'workers_with_no_car_adj',	'households_with_no_cars_adj',	'disabled_pop_adj',	
                                          'public_asst_pop_adj', 'inc_extremelylow_adj', 'inc_verylow_adj',	'inc_low_adj',	'male_seniors_adj',	
                                          'female_seniors_adj', 'male_youth_adj',  'female_youth_adj', 'veteran_pop_adj']]

filtered_final_data.head(2)

,name,organization_type,organization_name,analysis_name,ntd_id_y,ntd_id_2022_y,stop_id,stop_name,GEOIDFQ,geometry,area_2,total_pop_adj,poverty_pop_adj,non_us_citizen_adj,workers_with_no_car_adj,households_with_no_cars_adj,disabled_pop_adj,public_asst_pop_adj,inc_extremelylow_adj,inc_verylow_adj,inc_low_adj,male_seniors_adj,female_seniors_adj,male_youth_adj,female_youth_adj,veteran_pop_adj
0,AC Transit Schedule,None,None,None,None,None,4489,Broadway Av & Rivers St,1400000US06001423000,"POLYGON ((-199666.745 -13709.245, -199647.316 ...",730068.706503,4478.0,637.0,533.0,199.0,261.0,447.0,241.0,872.0,712.0,552.0,378.0,362.0,445.0,312.0,79.0
1,AC Transit Schedule,None,None,None,None,None,4489,Broadway Av & Rivers St,1400000US06001422200,"POLYGON ((-200507.136 -13116.597, -200491.926 ...",674019.805718,3313.0,188.0,217.0,62.0,173.0,320.0,57.0,480.0,309.0,310.0,157.0,256.0,89.0,113.0,51.0

## Agency Level Demography Data

In [45]:
group_key = ['name']

# Identify adjusted demographic columns
adj_cols = [col for col in geometry_intersect.columns if col.endswith('_adj')]

# Extra non-demographic attributes to keep (take first occurrence per agency)
extra_cols = ['organization_type', 'ntd_id_y', 'ntd_id_2022_y', 'key']

# Dissolve stop buffers to get agency shapes
agency_geometry = orgs_stop_dissolved.dissolve(by=group_key, as_index=False)

# --- DROP overlapping extra columns from agency_geometry ---
agency_geometry = agency_geometry.drop(columns=extra_cols, errors='ignore')

# Aggregate population metrics
agency_demo = geometry_intersect.groupby(group_key, as_index=False)[adj_cols].sum()

# Merge demographics with geometry
agency_summary = agency_geometry.merge(agency_demo, on=group_key, how='left')

# Merge extra attributes (take first)
extra_attrs = orgs_stop_dissolved[group_key + extra_cols].drop_duplicates(subset=group_key)
agency_summary = agency_summary.merge(extra_attrs, on=group_key, how='left')

In [46]:
agency_summary = gpd.GeoDataFrame(
    agency_summary,
    geometry='geometry',
    crs=tracts_ca_acs.crs
).to_crs(epsg=4326)

In [47]:
agency_summary = agency_summary.drop(columns=["ntd_id_x", "ntd_id_2022_x"])

agency_summary = agency_summary.rename(
    columns={
        "ntd_id_y": "ntd_id",
        "ntd_id_2022_y": "ntd_id_2022"
    }
)

In [48]:
agency_summary.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           279 non-null    object
 1   geometry                       279 non-null    geometry
 2   stop_id                        279 non-null    object
 3   stop_name                      279 non-null    object
 4   schedule_gtfs_dataset_name     203 non-null    object
 5   organization_source_record_id  214 non-null    object
 6   analysis_name                  215 non-null    object
 7   organization_name              203 non-null    object
 8   name_clean                     279 non-null    object
 9   source_record_id               174 non-null    object
 10  total_pop_adj                  279 non-null    float64
 11  poverty_pop_adj                279 non-null    float64
 12  non_us_citizen_adj             279 non-null    float64
 13  workers_with_no_car_adj        279 non-null    float64
 14  households_with_no_cars_adj    279 non-null    float64
 15  disabled_pop_adj               279 non-null    float64
 16  public_asst_pop_adj            279 non-null    float64
 17  inc_extremelylow_adj           279 non-null    float64
 18  inc_verylow_adj                279 non-null    float64
 19  inc_low_adj                    279 non-null    float64
 20  male_seniors_adj               279 non-null    float64
 21  female_seniors_adj             279 non-null    float64
 22  veteran_pop_adj                279 non-null    float64
 23  male_youth_adj                 279 non-null    float64
 24  female_youth_adj               279 non-null    float64
 25  organization_type              175 non-null    object
 26  ntd_id                         149 non-null    object
 27  ntd_id_2022                    151 non-null    object
 28  key                            175 non-null    object
dtypes: float64(15), geometry(1), object(13)
memory usage: 63.3+ KB

In [49]:
# Merge acs and ntd data 
merged_agency_ntd = (
    pd.merge(
        agency_summary,
        ridership_data_grouped,
        how='left',
        left_on='ntd_id_2022',
        right_on='ntd_id'
    )
    .sort_values(by='agency')
)

In [50]:
merged_agency_ntd = gpd.GeoDataFrame(
    merged_agency_ntd, 
    geometry='geometry', 
    crs=agency_summary.crs
)

In [51]:
agency_map_ntd = {
    "Plumas Transit Systems": {"ntd_id_2022": "91119", "upt": 29264, "voms": 6},
    "Redwood Coast Transit Authority": {"ntd_id_2022": "91097", "upt": 64681, "voms": 4},
    "Nevada County": {"ntd_id_2022": "91095", "upt": 146562, "voms": 17},
    "Lake Transit Authority": {"ntd_id_2022": "91053", "upt": 228536, "voms": 26},
    "Mendocino Transit Authority": {"ntd_id_2022": "91047", "upt": 153720, "voms": 20},
    "San Benito County Local Transportation Authority": {"ntd_id_2022": "91009", "upt": 81284, "voms": 19},
    "Tulare County Regional Transit Agency": {"ntd_id_2022": "90310", "upt": 677529, "voms": 45},
    "City of Baldwin Park": {"ntd_id_2022": "90251", "upt": 78209, "voms": 8},
    "Marin County Transit District": {"ntd_id_2022": "90234", "upt": 2867835, "voms": 72},
    "Anaheim Transportation Network": {"ntd_id_2022": "90211", "upt": 8696858, "voms": 62},
    "Eastern Contra Costa Transit Authority": {"ntd_id_2022": "90162", "upt": 1411611, "voms": 97},
    "Redding Area Bus Authority": {"ntd_id_2022": "90093", "upt": 503018, "voms": 23},
    "Sonoma County": {"ntd_id_2022": "90089", "upt": 787144, "voms": 56},
    "Yuba-Sutter Transit Authority": {"ntd_id_2022": "90061", "upt": 573966, "voms": 29},
    "San Diego Metropolitan Transit System, Airport, Flagship Cruises": {"ntd_id_2022": "90026", "upt": 75682794, "voms": 819},
    "Ventura County (VCTC, Gold Coast, Cities of Camarillo, Moorpark, Ojai, Simi Valley, Thousand Oaks)": {"ntd_id_2022": "90164", "upt": 454893, "voms": 42},    
    "Sacramento Regional Transit District": {"ntd_id_2022": "90019", "upt": 16361582, "voms": 387}
}

In [52]:
for agency, vals in agency_map_ntd.items():
    mask = merged_agency_ntd["analysis_name"].eq(agency)

    merged_agency_ntd.loc[mask, "ntd_id_2022"] = vals["ntd_id_2022"]
    merged_agency_ntd.loc[mask, "unlinked_passenger_trips_upt"] = vals["upt"]
    merged_agency_ntd.loc[mask, "agency_voms"] = vals["voms"]

In [53]:
updated = merged_agency_ntd[
    merged_agency_ntd["analysis_name"].isin(agency_map_ntd.keys())
]

In [54]:
merged_agency_ntd = merged_agency_ntd[['key', 'name', 'organization_type', 'organization_name', 'analysis_name', 'ntd_id_2022', 'agency', 'total_pop_adj', 'poverty_pop_adj', 'non_us_citizen_adj', 'workers_with_no_car_adj',
        'households_with_no_cars_adj', 'disabled_pop_adj',
       'public_asst_pop_adj', 'inc_extremelylow_adj', 'inc_verylow_adj',
       'inc_low_adj', 'male_seniors_adj', 'female_seniors_adj', 'male_youth_adj', 'female_youth_adj',
       'veteran_pop_adj',  'unlinked_passenger_trips_upt', 'agency_voms']]

In [55]:
#Store data in warehouse
with fs.open(f"{GCS_FILE_PATH}/transit_provider_dashboard/merged_agency_ntd.parquet", "wb") as f:
    merged_agency_ntd.to_parquet(f, index=False)

In [56]:
def export_gdf(gdf, filename: str, export_csv: bool = True):
    # Update the path
    gcs_target_path = f"{GCS_FILE_PATH}/transit_provider_dashboard/"

    # Export as Parquet
    parquet_file = f"{filename}.parquet"
    gdf.to_parquet(parquet_file, engine="pyarrow", index=False)
    
    fs.put(
        parquet_file,
        f"{gcs_target_path}{parquet_file}",
        token=credentials.token
    )
    os.remove(parquet_file)
    print(f"Saved Parquet: {gcs_target_path}{parquet_file}")
    
    if export_csv:
        # Export as CSV
        csv_file = f"{filename}.csv"
        gdf.to_csv(csv_file, index=False)
        
        fs.put(
            csv_file,
            f"{gcs_target_path}{csv_file}",
            token=credentials.token
        )
        os.remove(csv_file)
        print(f"Saved CSV: {gcs_target_path}{csv_file}")

In [57]:
# Store data in warehouse
export_gdf(merged_agency_ntd, "merged_agency_ntd")

Saved Parquet: gs://calitp-analytics-data/data-analyses/transit_provider_dashboard/merged_agency_ntd.parquet
Saved CSV: gs://calitp-analytics-data/data-analyses/transit_provider_dashboard/merged_agency_ntd.csv

In [57]:
# Store data in warehouse
export_gdf(orgs_stop_buffered, "organization_stops_buffered")

Saved Parquet: gs://calitp-analytics-data/data-analyses/transit_provider_dashboard/organization_stops_buffered.parquet
Saved CSV: gs://calitp-analytics-data/data-analyses/transit_provider_dashboard/organization_stops_buffered.csv

In [58]:
GCS__PUBLIC_FILE_PATH = f"{PUBLIC_GCS}transit_provider_dashboard/"

def export_gdf_public(gdf, filename: str, export_csv: bool = True, export_parquet: bool = True):
    # --- GeoJSON ---
    geojson_file = f"{GCS__PUBLIC_FILE_PATH}{filename}.geojson"
    geojson_str = gdf.to_json()
    with fsspec.open(geojson_file, 'w') as f_out:
        f_out.write(geojson_str)
    print(f"Saved GeoJSON: {geojson_file}")

    # --- Parquet ---
    if export_parquet:
        parquet_file = f"{filename}.parquet"
        gdf.to_parquet(parquet_file, engine="pyarrow", index=False)
        with fsspec.open(f"{GCS__PUBLIC_FILE_PATH}{filename}.parquet", 'wb') as f_out:
            with open(parquet_file, 'rb') as f_in:
                f_out.write(f_in.read())
        os.remove(parquet_file)
        print(f"Saved Parquet: {GCS__PUBLIC_FILE_PATH}{filename}.parquet")

In [59]:
def export_gdf_public_with_metadata(gdf, filename: str):
    """
    Export GeoDataFrame to a single XLSX file that includes:
    - Main data sheet
    - Metadata sheet describing the columns
    """
    
    # ---- Metadata dictionary ----
    metadata = {
        "key": "Unique identifier for the agency record.",
        "name": "Organization name.",
        "organization_type": "Type of organization (e.g., transit agency, nonprofit).",
        "geometry": "Spatial geometry for the agency boundary or location.",
        "ntd_id_2022": "National Transit Database ID for 2022 reporting.",
        "agency": "Transit agency name.",
        "gtfs_dataset_key": "Identifier linking to the GTFS dataset.",
        "total_pop_adj": "Adjusted total population.",
        "poverty_pop_adj": "Adjusted population living below the poverty level.",
        "non_us_citizen_adj": "Adjusted count of non-U.S. citizens.",
        "workers_with_no_car_adj": "Adjusted count of workers without access to a vehicle.",
        "households_with_no_cars_adj": "Adjusted number of households without a vehicle.",
        "disabled_pop_adj": "Adjusted population with disabilities.",
        "public_asst_pop_adj": "Adjusted population receiving public assistance.",
        "inc_extremelylow_adj": "Adjusted number of extremely low-income households.",
        "inc_verylow_adj": "Adjusted number of very low-income households.",
        "inc_low_adj": "Adjusted number of low-income households.",
        "male_seniors_adj": "Adjusted male senior population (65+).",
        "female_seniors_adj": "Adjusted female senior population (65+).",
        "male_youth_adj": "Adjusted male youth population (15-24).", 
        "female_youth_adj": "Adjusted female youth population (15-24).",
        "veteran_pop_adj": "Adjusted veteran population.",
        "unlinked_passenger_trips_upt": "Annual number of unlinked passenger trips.",
        "agency_voms": "Vehicles operated in maximum service (peak vehicles)."
    }



    metadata_df = pd.DataFrame(
        [(col, metadata.get(col, "")) for col in gdf.columns],
        columns=["column", "description"]
    )

    # ---- Local temporary file ----
    xlsx_file = f"{filename}.xlsx"

    # ---- Write XLSX with data + metadata ----
    with ExcelWriter(xlsx_file, engine="openpyxl") as writer:
        gdf.to_excel(writer, sheet_name="data", index=False)
        metadata_df.to_excel(writer, sheet_name="metadata", index=False)

    # ---- Upload to GCS ----
    gcs_path = f"{GCS__PUBLIC_FILE_PATH}{filename}.xlsx"

    with fsspec.open(gcs_path, "wb") as f_out:
        with open(xlsx_file, "rb") as f_in:
            f_out.write(f_in.read())

    os.remove(xlsx_file)

    print(f"Saved XLSX with metadata: {gcs_path}")

In [60]:
export_gdf_public(merged_agency_ntd, "transitprovider_acs_ridership_2024_data")

Saved GeoJSON: gs://calitp-publish-data-analysis/transit_provider_dashboard/transitprovider_acs_ridership_2024_data.geojson
Saved Parquet: gs://calitp-publish-data-analysis/transit_provider_dashboard/transitprovider_acs_ridership_2024_data.parquet

In [61]:
export_gdf_public_with_metadata(merged_agency_ntd, "transitprovider_acs_ridership_2024_data")

Saved XLSX with metadata: gs://calitp-publish-data-analysis/transit_provider_dashboard/transitprovider_acs_ridership_2024_data.xlsx